
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Employee: 'Employee',
  PayrollRun: 'PayrollRun',
  PayrollRecord: 'PayrollRecord',
  PayrollComponent: 'PayrollComponent',
  ValidationError: 'ValidationError'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const EmployeeScalarFieldEnum = {
  id: 'id',
  staffNumber: 'staffNumber',
  fullName: 'fullName',
  department: 'department',
  staffType: 'staffType',
  bankName: 'bankName',
  accountNumber: 'accountNumber',
  email: 'email',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EmployeeScalarFieldEnum = (typeof EmployeeScalarFieldEnum)[keyof typeof EmployeeScalarFieldEnum]


export const PayrollRunScalarFieldEnum = {
  id: 'id',
  month: 'month',
  year: 'year',
  uploadedAt: 'uploadedAt',
  uploadedBy: 'uploadedBy',
  processedAt: 'processedAt',
  status: 'status',
  notes: 'notes'
} as const

export type PayrollRunScalarFieldEnum = (typeof PayrollRunScalarFieldEnum)[keyof typeof PayrollRunScalarFieldEnum]


export const PayrollRecordScalarFieldEnum = {
  id: 'id',
  payrollRunId: 'payrollRunId',
  employeeId: 'employeeId',
  basicSalary: 'basicSalary',
  grossPay: 'grossPay',
  totalDeductions: 'totalDeductions',
  netPay: 'netPay',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PayrollRecordScalarFieldEnum = (typeof PayrollRecordScalarFieldEnum)[keyof typeof PayrollRecordScalarFieldEnum]


export const PayrollComponentScalarFieldEnum = {
  id: 'id',
  recordId: 'recordId',
  name: 'name',
  amount: 'amount',
  type: 'type',
  createdAt: 'createdAt'
} as const

export type PayrollComponentScalarFieldEnum = (typeof PayrollComponentScalarFieldEnum)[keyof typeof PayrollComponentScalarFieldEnum]


export const ValidationErrorScalarFieldEnum = {
  id: 'id',
  payrollRunId: 'payrollRunId',
  errorType: 'errorType',
  staffNumber: 'staffNumber',
  staffName: 'staffName',
  message: 'message',
  severity: 'severity',
  createdAt: 'createdAt'
} as const

export type ValidationErrorScalarFieldEnum = (typeof ValidationErrorScalarFieldEnum)[keyof typeof ValidationErrorScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

