
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const StaffType = {
  ACADEMIC: 'ACADEMIC',
  NON_ACADEMIC: 'NON_ACADEMIC'
} as const

export type StaffType = (typeof StaffType)[keyof typeof StaffType]


export const ComponentType = {
  INCOME: 'INCOME',
  DEDUCTION: 'DEDUCTION'
} as const

export type ComponentType = (typeof ComponentType)[keyof typeof ComponentType]
