
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PayrollComponent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PayrollComponent
 * 
 */
export type PayrollComponentModel = runtime.Types.Result.DefaultSelection<Prisma.$PayrollComponentPayload>

export type AggregatePayrollComponent = {
  _count: PayrollComponentCountAggregateOutputType | null
  _avg: PayrollComponentAvgAggregateOutputType | null
  _sum: PayrollComponentSumAggregateOutputType | null
  _min: PayrollComponentMinAggregateOutputType | null
  _max: PayrollComponentMaxAggregateOutputType | null
}

export type PayrollComponentAvgAggregateOutputType = {
  amount: runtime.Decimal | null
}

export type PayrollComponentSumAggregateOutputType = {
  amount: runtime.Decimal | null
}

export type PayrollComponentMinAggregateOutputType = {
  id: string | null
  recordId: string | null
  name: string | null
  amount: runtime.Decimal | null
  type: $Enums.ComponentType | null
  createdAt: Date | null
}

export type PayrollComponentMaxAggregateOutputType = {
  id: string | null
  recordId: string | null
  name: string | null
  amount: runtime.Decimal | null
  type: $Enums.ComponentType | null
  createdAt: Date | null
}

export type PayrollComponentCountAggregateOutputType = {
  id: number
  recordId: number
  name: number
  amount: number
  type: number
  createdAt: number
  _all: number
}


export type PayrollComponentAvgAggregateInputType = {
  amount?: true
}

export type PayrollComponentSumAggregateInputType = {
  amount?: true
}

export type PayrollComponentMinAggregateInputType = {
  id?: true
  recordId?: true
  name?: true
  amount?: true
  type?: true
  createdAt?: true
}

export type PayrollComponentMaxAggregateInputType = {
  id?: true
  recordId?: true
  name?: true
  amount?: true
  type?: true
  createdAt?: true
}

export type PayrollComponentCountAggregateInputType = {
  id?: true
  recordId?: true
  name?: true
  amount?: true
  type?: true
  createdAt?: true
  _all?: true
}

export type PayrollComponentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PayrollComponent to aggregate.
   */
  where?: Prisma.PayrollComponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollComponents to fetch.
   */
  orderBy?: Prisma.PayrollComponentOrderByWithRelationInput | Prisma.PayrollComponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PayrollComponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollComponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollComponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PayrollComponents
  **/
  _count?: true | PayrollComponentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PayrollComponentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PayrollComponentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PayrollComponentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PayrollComponentMaxAggregateInputType
}

export type GetPayrollComponentAggregateType<T extends PayrollComponentAggregateArgs> = {
      [P in keyof T & keyof AggregatePayrollComponent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePayrollComponent[P]>
    : Prisma.GetScalarType<T[P], AggregatePayrollComponent[P]>
}




export type PayrollComponentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PayrollComponentWhereInput
  orderBy?: Prisma.PayrollComponentOrderByWithAggregationInput | Prisma.PayrollComponentOrderByWithAggregationInput[]
  by: Prisma.PayrollComponentScalarFieldEnum[] | Prisma.PayrollComponentScalarFieldEnum
  having?: Prisma.PayrollComponentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PayrollComponentCountAggregateInputType | true
  _avg?: PayrollComponentAvgAggregateInputType
  _sum?: PayrollComponentSumAggregateInputType
  _min?: PayrollComponentMinAggregateInputType
  _max?: PayrollComponentMaxAggregateInputType
}

export type PayrollComponentGroupByOutputType = {
  id: string
  recordId: string
  name: string
  amount: runtime.Decimal
  type: $Enums.ComponentType
  createdAt: Date
  _count: PayrollComponentCountAggregateOutputType | null
  _avg: PayrollComponentAvgAggregateOutputType | null
  _sum: PayrollComponentSumAggregateOutputType | null
  _min: PayrollComponentMinAggregateOutputType | null
  _max: PayrollComponentMaxAggregateOutputType | null
}

type GetPayrollComponentGroupByPayload<T extends PayrollComponentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PayrollComponentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PayrollComponentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PayrollComponentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PayrollComponentGroupByOutputType[P]>
      }
    >
  >



export type PayrollComponentWhereInput = {
  AND?: Prisma.PayrollComponentWhereInput | Prisma.PayrollComponentWhereInput[]
  OR?: Prisma.PayrollComponentWhereInput[]
  NOT?: Prisma.PayrollComponentWhereInput | Prisma.PayrollComponentWhereInput[]
  id?: Prisma.StringFilter<"PayrollComponent"> | string
  recordId?: Prisma.StringFilter<"PayrollComponent"> | string
  name?: Prisma.StringFilter<"PayrollComponent"> | string
  amount?: Prisma.DecimalFilter<"PayrollComponent"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFilter<"PayrollComponent"> | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFilter<"PayrollComponent"> | Date | string
  record?: Prisma.XOR<Prisma.PayrollRecordScalarRelationFilter, Prisma.PayrollRecordWhereInput>
}

export type PayrollComponentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  record?: Prisma.PayrollRecordOrderByWithRelationInput
}

export type PayrollComponentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PayrollComponentWhereInput | Prisma.PayrollComponentWhereInput[]
  OR?: Prisma.PayrollComponentWhereInput[]
  NOT?: Prisma.PayrollComponentWhereInput | Prisma.PayrollComponentWhereInput[]
  recordId?: Prisma.StringFilter<"PayrollComponent"> | string
  name?: Prisma.StringFilter<"PayrollComponent"> | string
  amount?: Prisma.DecimalFilter<"PayrollComponent"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFilter<"PayrollComponent"> | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFilter<"PayrollComponent"> | Date | string
  record?: Prisma.XOR<Prisma.PayrollRecordScalarRelationFilter, Prisma.PayrollRecordWhereInput>
}, "id">

export type PayrollComponentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PayrollComponentCountOrderByAggregateInput
  _avg?: Prisma.PayrollComponentAvgOrderByAggregateInput
  _max?: Prisma.PayrollComponentMaxOrderByAggregateInput
  _min?: Prisma.PayrollComponentMinOrderByAggregateInput
  _sum?: Prisma.PayrollComponentSumOrderByAggregateInput
}

export type PayrollComponentScalarWhereWithAggregatesInput = {
  AND?: Prisma.PayrollComponentScalarWhereWithAggregatesInput | Prisma.PayrollComponentScalarWhereWithAggregatesInput[]
  OR?: Prisma.PayrollComponentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PayrollComponentScalarWhereWithAggregatesInput | Prisma.PayrollComponentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PayrollComponent"> | string
  recordId?: Prisma.StringWithAggregatesFilter<"PayrollComponent"> | string
  name?: Prisma.StringWithAggregatesFilter<"PayrollComponent"> | string
  amount?: Prisma.DecimalWithAggregatesFilter<"PayrollComponent"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeWithAggregatesFilter<"PayrollComponent"> | $Enums.ComponentType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PayrollComponent"> | Date | string
}

export type PayrollComponentCreateInput = {
  id?: string
  name: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  type: $Enums.ComponentType
  createdAt?: Date | string
  record: Prisma.PayrollRecordCreateNestedOneWithoutComponentsInput
}

export type PayrollComponentUncheckedCreateInput = {
  id?: string
  recordId: string
  name: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  type: $Enums.ComponentType
  createdAt?: Date | string
}

export type PayrollComponentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFieldUpdateOperationsInput | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  record?: Prisma.PayrollRecordUpdateOneRequiredWithoutComponentsNestedInput
}

export type PayrollComponentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFieldUpdateOperationsInput | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollComponentCreateManyInput = {
  id?: string
  recordId: string
  name: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  type: $Enums.ComponentType
  createdAt?: Date | string
}

export type PayrollComponentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFieldUpdateOperationsInput | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollComponentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFieldUpdateOperationsInput | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollComponentListRelationFilter = {
  every?: Prisma.PayrollComponentWhereInput
  some?: Prisma.PayrollComponentWhereInput
  none?: Prisma.PayrollComponentWhereInput
}

export type PayrollComponentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PayrollComponentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PayrollComponentAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PayrollComponentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PayrollComponentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PayrollComponentSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PayrollComponentCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.PayrollComponentCreateWithoutRecordInput, Prisma.PayrollComponentUncheckedCreateWithoutRecordInput> | Prisma.PayrollComponentCreateWithoutRecordInput[] | Prisma.PayrollComponentUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.PayrollComponentCreateOrConnectWithoutRecordInput | Prisma.PayrollComponentCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.PayrollComponentCreateManyRecordInputEnvelope
  connect?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
}

export type PayrollComponentUncheckedCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.PayrollComponentCreateWithoutRecordInput, Prisma.PayrollComponentUncheckedCreateWithoutRecordInput> | Prisma.PayrollComponentCreateWithoutRecordInput[] | Prisma.PayrollComponentUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.PayrollComponentCreateOrConnectWithoutRecordInput | Prisma.PayrollComponentCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.PayrollComponentCreateManyRecordInputEnvelope
  connect?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
}

export type PayrollComponentUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.PayrollComponentCreateWithoutRecordInput, Prisma.PayrollComponentUncheckedCreateWithoutRecordInput> | Prisma.PayrollComponentCreateWithoutRecordInput[] | Prisma.PayrollComponentUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.PayrollComponentCreateOrConnectWithoutRecordInput | Prisma.PayrollComponentCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.PayrollComponentUpsertWithWhereUniqueWithoutRecordInput | Prisma.PayrollComponentUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.PayrollComponentCreateManyRecordInputEnvelope
  set?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
  disconnect?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
  delete?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
  connect?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
  update?: Prisma.PayrollComponentUpdateWithWhereUniqueWithoutRecordInput | Prisma.PayrollComponentUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.PayrollComponentUpdateManyWithWhereWithoutRecordInput | Prisma.PayrollComponentUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.PayrollComponentScalarWhereInput | Prisma.PayrollComponentScalarWhereInput[]
}

export type PayrollComponentUncheckedUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.PayrollComponentCreateWithoutRecordInput, Prisma.PayrollComponentUncheckedCreateWithoutRecordInput> | Prisma.PayrollComponentCreateWithoutRecordInput[] | Prisma.PayrollComponentUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.PayrollComponentCreateOrConnectWithoutRecordInput | Prisma.PayrollComponentCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.PayrollComponentUpsertWithWhereUniqueWithoutRecordInput | Prisma.PayrollComponentUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.PayrollComponentCreateManyRecordInputEnvelope
  set?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
  disconnect?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
  delete?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
  connect?: Prisma.PayrollComponentWhereUniqueInput | Prisma.PayrollComponentWhereUniqueInput[]
  update?: Prisma.PayrollComponentUpdateWithWhereUniqueWithoutRecordInput | Prisma.PayrollComponentUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.PayrollComponentUpdateManyWithWhereWithoutRecordInput | Prisma.PayrollComponentUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.PayrollComponentScalarWhereInput | Prisma.PayrollComponentScalarWhereInput[]
}

export type EnumComponentTypeFieldUpdateOperationsInput = {
  set?: $Enums.ComponentType
}

export type PayrollComponentCreateWithoutRecordInput = {
  id?: string
  name: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  type: $Enums.ComponentType
  createdAt?: Date | string
}

export type PayrollComponentUncheckedCreateWithoutRecordInput = {
  id?: string
  name: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  type: $Enums.ComponentType
  createdAt?: Date | string
}

export type PayrollComponentCreateOrConnectWithoutRecordInput = {
  where: Prisma.PayrollComponentWhereUniqueInput
  create: Prisma.XOR<Prisma.PayrollComponentCreateWithoutRecordInput, Prisma.PayrollComponentUncheckedCreateWithoutRecordInput>
}

export type PayrollComponentCreateManyRecordInputEnvelope = {
  data: Prisma.PayrollComponentCreateManyRecordInput | Prisma.PayrollComponentCreateManyRecordInput[]
  skipDuplicates?: boolean
}

export type PayrollComponentUpsertWithWhereUniqueWithoutRecordInput = {
  where: Prisma.PayrollComponentWhereUniqueInput
  update: Prisma.XOR<Prisma.PayrollComponentUpdateWithoutRecordInput, Prisma.PayrollComponentUncheckedUpdateWithoutRecordInput>
  create: Prisma.XOR<Prisma.PayrollComponentCreateWithoutRecordInput, Prisma.PayrollComponentUncheckedCreateWithoutRecordInput>
}

export type PayrollComponentUpdateWithWhereUniqueWithoutRecordInput = {
  where: Prisma.PayrollComponentWhereUniqueInput
  data: Prisma.XOR<Prisma.PayrollComponentUpdateWithoutRecordInput, Prisma.PayrollComponentUncheckedUpdateWithoutRecordInput>
}

export type PayrollComponentUpdateManyWithWhereWithoutRecordInput = {
  where: Prisma.PayrollComponentScalarWhereInput
  data: Prisma.XOR<Prisma.PayrollComponentUpdateManyMutationInput, Prisma.PayrollComponentUncheckedUpdateManyWithoutRecordInput>
}

export type PayrollComponentScalarWhereInput = {
  AND?: Prisma.PayrollComponentScalarWhereInput | Prisma.PayrollComponentScalarWhereInput[]
  OR?: Prisma.PayrollComponentScalarWhereInput[]
  NOT?: Prisma.PayrollComponentScalarWhereInput | Prisma.PayrollComponentScalarWhereInput[]
  id?: Prisma.StringFilter<"PayrollComponent"> | string
  recordId?: Prisma.StringFilter<"PayrollComponent"> | string
  name?: Prisma.StringFilter<"PayrollComponent"> | string
  amount?: Prisma.DecimalFilter<"PayrollComponent"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFilter<"PayrollComponent"> | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFilter<"PayrollComponent"> | Date | string
}

export type PayrollComponentCreateManyRecordInput = {
  id?: string
  name: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  type: $Enums.ComponentType
  createdAt?: Date | string
}

export type PayrollComponentUpdateWithoutRecordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFieldUpdateOperationsInput | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollComponentUncheckedUpdateWithoutRecordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFieldUpdateOperationsInput | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollComponentUncheckedUpdateManyWithoutRecordInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  type?: Prisma.EnumComponentTypeFieldUpdateOperationsInput | $Enums.ComponentType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PayrollComponentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  recordId?: boolean
  name?: boolean
  amount?: boolean
  type?: boolean
  createdAt?: boolean
  record?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payrollComponent"]>

export type PayrollComponentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  recordId?: boolean
  name?: boolean
  amount?: boolean
  type?: boolean
  createdAt?: boolean
  record?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payrollComponent"]>

export type PayrollComponentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  recordId?: boolean
  name?: boolean
  amount?: boolean
  type?: boolean
  createdAt?: boolean
  record?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payrollComponent"]>

export type PayrollComponentSelectScalar = {
  id?: boolean
  recordId?: boolean
  name?: boolean
  amount?: boolean
  type?: boolean
  createdAt?: boolean
}

export type PayrollComponentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "recordId" | "name" | "amount" | "type" | "createdAt", ExtArgs["result"]["payrollComponent"]>
export type PayrollComponentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}
export type PayrollComponentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}
export type PayrollComponentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}

export type $PayrollComponentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PayrollComponent"
  objects: {
    record: Prisma.$PayrollRecordPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    recordId: string
    name: string
    amount: runtime.Decimal
    type: $Enums.ComponentType
    createdAt: Date
  }, ExtArgs["result"]["payrollComponent"]>
  composites: {}
}

export type PayrollComponentGetPayload<S extends boolean | null | undefined | PayrollComponentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload, S>

export type PayrollComponentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PayrollComponentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PayrollComponentCountAggregateInputType | true
  }

export interface PayrollComponentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PayrollComponent'], meta: { name: 'PayrollComponent' } }
  /**
   * Find zero or one PayrollComponent that matches the filter.
   * @param {PayrollComponentFindUniqueArgs} args - Arguments to find a PayrollComponent
   * @example
   * // Get one PayrollComponent
   * const payrollComponent = await prisma.payrollComponent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PayrollComponentFindUniqueArgs>(args: Prisma.SelectSubset<T, PayrollComponentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PayrollComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PayrollComponent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PayrollComponentFindUniqueOrThrowArgs} args - Arguments to find a PayrollComponent
   * @example
   * // Get one PayrollComponent
   * const payrollComponent = await prisma.payrollComponent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PayrollComponentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PayrollComponentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PayrollComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PayrollComponent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollComponentFindFirstArgs} args - Arguments to find a PayrollComponent
   * @example
   * // Get one PayrollComponent
   * const payrollComponent = await prisma.payrollComponent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PayrollComponentFindFirstArgs>(args?: Prisma.SelectSubset<T, PayrollComponentFindFirstArgs<ExtArgs>>): Prisma.Prisma__PayrollComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PayrollComponent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollComponentFindFirstOrThrowArgs} args - Arguments to find a PayrollComponent
   * @example
   * // Get one PayrollComponent
   * const payrollComponent = await prisma.payrollComponent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PayrollComponentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PayrollComponentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PayrollComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PayrollComponents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollComponentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PayrollComponents
   * const payrollComponents = await prisma.payrollComponent.findMany()
   * 
   * // Get first 10 PayrollComponents
   * const payrollComponents = await prisma.payrollComponent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const payrollComponentWithIdOnly = await prisma.payrollComponent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PayrollComponentFindManyArgs>(args?: Prisma.SelectSubset<T, PayrollComponentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PayrollComponent.
   * @param {PayrollComponentCreateArgs} args - Arguments to create a PayrollComponent.
   * @example
   * // Create one PayrollComponent
   * const PayrollComponent = await prisma.payrollComponent.create({
   *   data: {
   *     // ... data to create a PayrollComponent
   *   }
   * })
   * 
   */
  create<T extends PayrollComponentCreateArgs>(args: Prisma.SelectSubset<T, PayrollComponentCreateArgs<ExtArgs>>): Prisma.Prisma__PayrollComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PayrollComponents.
   * @param {PayrollComponentCreateManyArgs} args - Arguments to create many PayrollComponents.
   * @example
   * // Create many PayrollComponents
   * const payrollComponent = await prisma.payrollComponent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PayrollComponentCreateManyArgs>(args?: Prisma.SelectSubset<T, PayrollComponentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PayrollComponents and returns the data saved in the database.
   * @param {PayrollComponentCreateManyAndReturnArgs} args - Arguments to create many PayrollComponents.
   * @example
   * // Create many PayrollComponents
   * const payrollComponent = await prisma.payrollComponent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PayrollComponents and only return the `id`
   * const payrollComponentWithIdOnly = await prisma.payrollComponent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PayrollComponentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PayrollComponentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PayrollComponent.
   * @param {PayrollComponentDeleteArgs} args - Arguments to delete one PayrollComponent.
   * @example
   * // Delete one PayrollComponent
   * const PayrollComponent = await prisma.payrollComponent.delete({
   *   where: {
   *     // ... filter to delete one PayrollComponent
   *   }
   * })
   * 
   */
  delete<T extends PayrollComponentDeleteArgs>(args: Prisma.SelectSubset<T, PayrollComponentDeleteArgs<ExtArgs>>): Prisma.Prisma__PayrollComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PayrollComponent.
   * @param {PayrollComponentUpdateArgs} args - Arguments to update one PayrollComponent.
   * @example
   * // Update one PayrollComponent
   * const payrollComponent = await prisma.payrollComponent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PayrollComponentUpdateArgs>(args: Prisma.SelectSubset<T, PayrollComponentUpdateArgs<ExtArgs>>): Prisma.Prisma__PayrollComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PayrollComponents.
   * @param {PayrollComponentDeleteManyArgs} args - Arguments to filter PayrollComponents to delete.
   * @example
   * // Delete a few PayrollComponents
   * const { count } = await prisma.payrollComponent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PayrollComponentDeleteManyArgs>(args?: Prisma.SelectSubset<T, PayrollComponentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PayrollComponents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollComponentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PayrollComponents
   * const payrollComponent = await prisma.payrollComponent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PayrollComponentUpdateManyArgs>(args: Prisma.SelectSubset<T, PayrollComponentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PayrollComponents and returns the data updated in the database.
   * @param {PayrollComponentUpdateManyAndReturnArgs} args - Arguments to update many PayrollComponents.
   * @example
   * // Update many PayrollComponents
   * const payrollComponent = await prisma.payrollComponent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PayrollComponents and only return the `id`
   * const payrollComponentWithIdOnly = await prisma.payrollComponent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PayrollComponentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PayrollComponentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PayrollComponent.
   * @param {PayrollComponentUpsertArgs} args - Arguments to update or create a PayrollComponent.
   * @example
   * // Update or create a PayrollComponent
   * const payrollComponent = await prisma.payrollComponent.upsert({
   *   create: {
   *     // ... data to create a PayrollComponent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PayrollComponent we want to update
   *   }
   * })
   */
  upsert<T extends PayrollComponentUpsertArgs>(args: Prisma.SelectSubset<T, PayrollComponentUpsertArgs<ExtArgs>>): Prisma.Prisma__PayrollComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PayrollComponents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollComponentCountArgs} args - Arguments to filter PayrollComponents to count.
   * @example
   * // Count the number of PayrollComponents
   * const count = await prisma.payrollComponent.count({
   *   where: {
   *     // ... the filter for the PayrollComponents we want to count
   *   }
   * })
  **/
  count<T extends PayrollComponentCountArgs>(
    args?: Prisma.Subset<T, PayrollComponentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PayrollComponentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PayrollComponent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollComponentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PayrollComponentAggregateArgs>(args: Prisma.Subset<T, PayrollComponentAggregateArgs>): Prisma.PrismaPromise<GetPayrollComponentAggregateType<T>>

  /**
   * Group by PayrollComponent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollComponentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PayrollComponentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PayrollComponentGroupByArgs['orderBy'] }
      : { orderBy?: PayrollComponentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PayrollComponentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPayrollComponentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PayrollComponent model
 */
readonly fields: PayrollComponentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PayrollComponent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PayrollComponentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  record<T extends Prisma.PayrollRecordDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PayrollRecordDefaultArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PayrollComponent model
 */
export interface PayrollComponentFieldRefs {
  readonly id: Prisma.FieldRef<"PayrollComponent", 'String'>
  readonly recordId: Prisma.FieldRef<"PayrollComponent", 'String'>
  readonly name: Prisma.FieldRef<"PayrollComponent", 'String'>
  readonly amount: Prisma.FieldRef<"PayrollComponent", 'Decimal'>
  readonly type: Prisma.FieldRef<"PayrollComponent", 'ComponentType'>
  readonly createdAt: Prisma.FieldRef<"PayrollComponent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PayrollComponent findUnique
 */
export type PayrollComponentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollComponent to fetch.
   */
  where: Prisma.PayrollComponentWhereUniqueInput
}

/**
 * PayrollComponent findUniqueOrThrow
 */
export type PayrollComponentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollComponent to fetch.
   */
  where: Prisma.PayrollComponentWhereUniqueInput
}

/**
 * PayrollComponent findFirst
 */
export type PayrollComponentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollComponent to fetch.
   */
  where?: Prisma.PayrollComponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollComponents to fetch.
   */
  orderBy?: Prisma.PayrollComponentOrderByWithRelationInput | Prisma.PayrollComponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PayrollComponents.
   */
  cursor?: Prisma.PayrollComponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollComponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollComponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayrollComponents.
   */
  distinct?: Prisma.PayrollComponentScalarFieldEnum | Prisma.PayrollComponentScalarFieldEnum[]
}

/**
 * PayrollComponent findFirstOrThrow
 */
export type PayrollComponentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollComponent to fetch.
   */
  where?: Prisma.PayrollComponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollComponents to fetch.
   */
  orderBy?: Prisma.PayrollComponentOrderByWithRelationInput | Prisma.PayrollComponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PayrollComponents.
   */
  cursor?: Prisma.PayrollComponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollComponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollComponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayrollComponents.
   */
  distinct?: Prisma.PayrollComponentScalarFieldEnum | Prisma.PayrollComponentScalarFieldEnum[]
}

/**
 * PayrollComponent findMany
 */
export type PayrollComponentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollComponents to fetch.
   */
  where?: Prisma.PayrollComponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollComponents to fetch.
   */
  orderBy?: Prisma.PayrollComponentOrderByWithRelationInput | Prisma.PayrollComponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PayrollComponents.
   */
  cursor?: Prisma.PayrollComponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollComponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollComponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayrollComponents.
   */
  distinct?: Prisma.PayrollComponentScalarFieldEnum | Prisma.PayrollComponentScalarFieldEnum[]
}

/**
 * PayrollComponent create
 */
export type PayrollComponentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
  /**
   * The data needed to create a PayrollComponent.
   */
  data: Prisma.XOR<Prisma.PayrollComponentCreateInput, Prisma.PayrollComponentUncheckedCreateInput>
}

/**
 * PayrollComponent createMany
 */
export type PayrollComponentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PayrollComponents.
   */
  data: Prisma.PayrollComponentCreateManyInput | Prisma.PayrollComponentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PayrollComponent createManyAndReturn
 */
export type PayrollComponentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * The data used to create many PayrollComponents.
   */
  data: Prisma.PayrollComponentCreateManyInput | Prisma.PayrollComponentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PayrollComponent update
 */
export type PayrollComponentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
  /**
   * The data needed to update a PayrollComponent.
   */
  data: Prisma.XOR<Prisma.PayrollComponentUpdateInput, Prisma.PayrollComponentUncheckedUpdateInput>
  /**
   * Choose, which PayrollComponent to update.
   */
  where: Prisma.PayrollComponentWhereUniqueInput
}

/**
 * PayrollComponent updateMany
 */
export type PayrollComponentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PayrollComponents.
   */
  data: Prisma.XOR<Prisma.PayrollComponentUpdateManyMutationInput, Prisma.PayrollComponentUncheckedUpdateManyInput>
  /**
   * Filter which PayrollComponents to update
   */
  where?: Prisma.PayrollComponentWhereInput
  /**
   * Limit how many PayrollComponents to update.
   */
  limit?: number
}

/**
 * PayrollComponent updateManyAndReturn
 */
export type PayrollComponentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * The data used to update PayrollComponents.
   */
  data: Prisma.XOR<Prisma.PayrollComponentUpdateManyMutationInput, Prisma.PayrollComponentUncheckedUpdateManyInput>
  /**
   * Filter which PayrollComponents to update
   */
  where?: Prisma.PayrollComponentWhereInput
  /**
   * Limit how many PayrollComponents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PayrollComponent upsert
 */
export type PayrollComponentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
  /**
   * The filter to search for the PayrollComponent to update in case it exists.
   */
  where: Prisma.PayrollComponentWhereUniqueInput
  /**
   * In case the PayrollComponent found by the `where` argument doesn't exist, create a new PayrollComponent with this data.
   */
  create: Prisma.XOR<Prisma.PayrollComponentCreateInput, Prisma.PayrollComponentUncheckedCreateInput>
  /**
   * In case the PayrollComponent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PayrollComponentUpdateInput, Prisma.PayrollComponentUncheckedUpdateInput>
}

/**
 * PayrollComponent delete
 */
export type PayrollComponentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
  /**
   * Filter which PayrollComponent to delete.
   */
  where: Prisma.PayrollComponentWhereUniqueInput
}

/**
 * PayrollComponent deleteMany
 */
export type PayrollComponentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PayrollComponents to delete
   */
  where?: Prisma.PayrollComponentWhereInput
  /**
   * Limit how many PayrollComponents to delete.
   */
  limit?: number
}

/**
 * PayrollComponent without action
 */
export type PayrollComponentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollComponent
   */
  select?: Prisma.PayrollComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollComponent
   */
  omit?: Prisma.PayrollComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollComponentInclude<ExtArgs> | null
}
