
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PayrollRecordComponent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PayrollRecordComponent
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type PayrollRecordComponentModel = runtime.Types.Result.DefaultSelection<Prisma.$PayrollRecordComponentPayload>

export type AggregatePayrollRecordComponent = {
  _count: PayrollRecordComponentCountAggregateOutputType | null
  _avg: PayrollRecordComponentAvgAggregateOutputType | null
  _sum: PayrollRecordComponentSumAggregateOutputType | null
  _min: PayrollRecordComponentMinAggregateOutputType | null
  _max: PayrollRecordComponentMaxAggregateOutputType | null
}

export type PayrollRecordComponentAvgAggregateOutputType = {
  id: number | null
  payrollRecordId: number | null
  componentId: number | null
  amount: runtime.Decimal | null
}

export type PayrollRecordComponentSumAggregateOutputType = {
  id: number | null
  payrollRecordId: number | null
  componentId: number | null
  amount: runtime.Decimal | null
}

export type PayrollRecordComponentMinAggregateOutputType = {
  id: number | null
  payrollRecordId: number | null
  componentId: number | null
  amount: runtime.Decimal | null
  createdAt: Date | null
}

export type PayrollRecordComponentMaxAggregateOutputType = {
  id: number | null
  payrollRecordId: number | null
  componentId: number | null
  amount: runtime.Decimal | null
  createdAt: Date | null
}

export type PayrollRecordComponentCountAggregateOutputType = {
  id: number
  payrollRecordId: number
  componentId: number
  amount: number
  createdAt: number
  _all: number
}


export type PayrollRecordComponentAvgAggregateInputType = {
  id?: true
  payrollRecordId?: true
  componentId?: true
  amount?: true
}

export type PayrollRecordComponentSumAggregateInputType = {
  id?: true
  payrollRecordId?: true
  componentId?: true
  amount?: true
}

export type PayrollRecordComponentMinAggregateInputType = {
  id?: true
  payrollRecordId?: true
  componentId?: true
  amount?: true
  createdAt?: true
}

export type PayrollRecordComponentMaxAggregateInputType = {
  id?: true
  payrollRecordId?: true
  componentId?: true
  amount?: true
  createdAt?: true
}

export type PayrollRecordComponentCountAggregateInputType = {
  id?: true
  payrollRecordId?: true
  componentId?: true
  amount?: true
  createdAt?: true
  _all?: true
}

export type PayrollRecordComponentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PayrollRecordComponent to aggregate.
   */
  where?: Prisma.PayrollRecordComponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollRecordComponents to fetch.
   */
  orderBy?: Prisma.PayrollRecordComponentOrderByWithRelationInput | Prisma.PayrollRecordComponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PayrollRecordComponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollRecordComponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollRecordComponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PayrollRecordComponents
  **/
  _count?: true | PayrollRecordComponentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PayrollRecordComponentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PayrollRecordComponentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PayrollRecordComponentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PayrollRecordComponentMaxAggregateInputType
}

export type GetPayrollRecordComponentAggregateType<T extends PayrollRecordComponentAggregateArgs> = {
      [P in keyof T & keyof AggregatePayrollRecordComponent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePayrollRecordComponent[P]>
    : Prisma.GetScalarType<T[P], AggregatePayrollRecordComponent[P]>
}




export type PayrollRecordComponentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PayrollRecordComponentWhereInput
  orderBy?: Prisma.PayrollRecordComponentOrderByWithAggregationInput | Prisma.PayrollRecordComponentOrderByWithAggregationInput[]
  by: Prisma.PayrollRecordComponentScalarFieldEnum[] | Prisma.PayrollRecordComponentScalarFieldEnum
  having?: Prisma.PayrollRecordComponentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PayrollRecordComponentCountAggregateInputType | true
  _avg?: PayrollRecordComponentAvgAggregateInputType
  _sum?: PayrollRecordComponentSumAggregateInputType
  _min?: PayrollRecordComponentMinAggregateInputType
  _max?: PayrollRecordComponentMaxAggregateInputType
}

export type PayrollRecordComponentGroupByOutputType = {
  id: number
  payrollRecordId: number
  componentId: number
  amount: runtime.Decimal
  createdAt: Date
  _count: PayrollRecordComponentCountAggregateOutputType | null
  _avg: PayrollRecordComponentAvgAggregateOutputType | null
  _sum: PayrollRecordComponentSumAggregateOutputType | null
  _min: PayrollRecordComponentMinAggregateOutputType | null
  _max: PayrollRecordComponentMaxAggregateOutputType | null
}

type GetPayrollRecordComponentGroupByPayload<T extends PayrollRecordComponentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PayrollRecordComponentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PayrollRecordComponentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PayrollRecordComponentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PayrollRecordComponentGroupByOutputType[P]>
      }
    >
  >



export type PayrollRecordComponentWhereInput = {
  AND?: Prisma.PayrollRecordComponentWhereInput | Prisma.PayrollRecordComponentWhereInput[]
  OR?: Prisma.PayrollRecordComponentWhereInput[]
  NOT?: Prisma.PayrollRecordComponentWhereInput | Prisma.PayrollRecordComponentWhereInput[]
  id?: Prisma.IntFilter<"PayrollRecordComponent"> | number
  payrollRecordId?: Prisma.IntFilter<"PayrollRecordComponent"> | number
  componentId?: Prisma.IntFilter<"PayrollRecordComponent"> | number
  amount?: Prisma.DecimalFilter<"PayrollRecordComponent"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"PayrollRecordComponent"> | Date | string
  PayrollComponent?: Prisma.XOR<Prisma.PayrollComponentScalarRelationFilter, Prisma.PayrollComponentWhereInput>
  PayrollRecord?: Prisma.XOR<Prisma.PayrollRecordScalarRelationFilter, Prisma.PayrollRecordWhereInput>
}

export type PayrollRecordComponentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  payrollRecordId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  PayrollComponent?: Prisma.PayrollComponentOrderByWithRelationInput
  PayrollRecord?: Prisma.PayrollRecordOrderByWithRelationInput
}

export type PayrollRecordComponentWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  payrollRecordId_componentId?: Prisma.PayrollRecordComponentPayrollRecordIdComponentIdCompoundUniqueInput
  AND?: Prisma.PayrollRecordComponentWhereInput | Prisma.PayrollRecordComponentWhereInput[]
  OR?: Prisma.PayrollRecordComponentWhereInput[]
  NOT?: Prisma.PayrollRecordComponentWhereInput | Prisma.PayrollRecordComponentWhereInput[]
  payrollRecordId?: Prisma.IntFilter<"PayrollRecordComponent"> | number
  componentId?: Prisma.IntFilter<"PayrollRecordComponent"> | number
  amount?: Prisma.DecimalFilter<"PayrollRecordComponent"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"PayrollRecordComponent"> | Date | string
  PayrollComponent?: Prisma.XOR<Prisma.PayrollComponentScalarRelationFilter, Prisma.PayrollComponentWhereInput>
  PayrollRecord?: Prisma.XOR<Prisma.PayrollRecordScalarRelationFilter, Prisma.PayrollRecordWhereInput>
}, "id" | "payrollRecordId_componentId">

export type PayrollRecordComponentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  payrollRecordId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PayrollRecordComponentCountOrderByAggregateInput
  _avg?: Prisma.PayrollRecordComponentAvgOrderByAggregateInput
  _max?: Prisma.PayrollRecordComponentMaxOrderByAggregateInput
  _min?: Prisma.PayrollRecordComponentMinOrderByAggregateInput
  _sum?: Prisma.PayrollRecordComponentSumOrderByAggregateInput
}

export type PayrollRecordComponentScalarWhereWithAggregatesInput = {
  AND?: Prisma.PayrollRecordComponentScalarWhereWithAggregatesInput | Prisma.PayrollRecordComponentScalarWhereWithAggregatesInput[]
  OR?: Prisma.PayrollRecordComponentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PayrollRecordComponentScalarWhereWithAggregatesInput | Prisma.PayrollRecordComponentScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PayrollRecordComponent"> | number
  payrollRecordId?: Prisma.IntWithAggregatesFilter<"PayrollRecordComponent"> | number
  componentId?: Prisma.IntWithAggregatesFilter<"PayrollRecordComponent"> | number
  amount?: Prisma.DecimalWithAggregatesFilter<"PayrollRecordComponent"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PayrollRecordComponent"> | Date | string
}

export type PayrollRecordComponentCreateInput = {
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  PayrollComponent: Prisma.PayrollComponentCreateNestedOneWithoutPayrollRecordComponentInput
  PayrollRecord: Prisma.PayrollRecordCreateNestedOneWithoutPayrollRecordComponentInput
}

export type PayrollRecordComponentUncheckedCreateInput = {
  id?: number
  payrollRecordId: number
  componentId: number
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type PayrollRecordComponentUpdateInput = {
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  PayrollComponent?: Prisma.PayrollComponentUpdateOneRequiredWithoutPayrollRecordComponentNestedInput
  PayrollRecord?: Prisma.PayrollRecordUpdateOneRequiredWithoutPayrollRecordComponentNestedInput
}

export type PayrollRecordComponentUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  payrollRecordId?: Prisma.IntFieldUpdateOperationsInput | number
  componentId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollRecordComponentCreateManyInput = {
  id?: number
  payrollRecordId: number
  componentId: number
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type PayrollRecordComponentUpdateManyMutationInput = {
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollRecordComponentUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  payrollRecordId?: Prisma.IntFieldUpdateOperationsInput | number
  componentId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollRecordComponentListRelationFilter = {
  every?: Prisma.PayrollRecordComponentWhereInput
  some?: Prisma.PayrollRecordComponentWhereInput
  none?: Prisma.PayrollRecordComponentWhereInput
}

export type PayrollRecordComponentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PayrollRecordComponentPayrollRecordIdComponentIdCompoundUniqueInput = {
  payrollRecordId: number
  componentId: number
}

export type PayrollRecordComponentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payrollRecordId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PayrollRecordComponentAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payrollRecordId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type PayrollRecordComponentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payrollRecordId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PayrollRecordComponentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payrollRecordId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PayrollRecordComponentSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payrollRecordId?: Prisma.SortOrder
  componentId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type PayrollRecordComponentCreateNestedManyWithoutPayrollRecordInput = {
  create?: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput> | Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput[] | Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput[]
  connectOrCreate?: Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollRecordInput | Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollRecordInput[]
  createMany?: Prisma.PayrollRecordComponentCreateManyPayrollRecordInputEnvelope
  connect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
}

export type PayrollRecordComponentUncheckedCreateNestedManyWithoutPayrollRecordInput = {
  create?: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput> | Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput[] | Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput[]
  connectOrCreate?: Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollRecordInput | Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollRecordInput[]
  createMany?: Prisma.PayrollRecordComponentCreateManyPayrollRecordInputEnvelope
  connect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
}

export type PayrollRecordComponentUpdateManyWithoutPayrollRecordNestedInput = {
  create?: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput> | Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput[] | Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput[]
  connectOrCreate?: Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollRecordInput | Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollRecordInput[]
  upsert?: Prisma.PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollRecordInput | Prisma.PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollRecordInput[]
  createMany?: Prisma.PayrollRecordComponentCreateManyPayrollRecordInputEnvelope
  set?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  disconnect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  delete?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  connect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  update?: Prisma.PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollRecordInput | Prisma.PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollRecordInput[]
  updateMany?: Prisma.PayrollRecordComponentUpdateManyWithWhereWithoutPayrollRecordInput | Prisma.PayrollRecordComponentUpdateManyWithWhereWithoutPayrollRecordInput[]
  deleteMany?: Prisma.PayrollRecordComponentScalarWhereInput | Prisma.PayrollRecordComponentScalarWhereInput[]
}

export type PayrollRecordComponentUncheckedUpdateManyWithoutPayrollRecordNestedInput = {
  create?: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput> | Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput[] | Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput[]
  connectOrCreate?: Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollRecordInput | Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollRecordInput[]
  upsert?: Prisma.PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollRecordInput | Prisma.PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollRecordInput[]
  createMany?: Prisma.PayrollRecordComponentCreateManyPayrollRecordInputEnvelope
  set?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  disconnect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  delete?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  connect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  update?: Prisma.PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollRecordInput | Prisma.PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollRecordInput[]
  updateMany?: Prisma.PayrollRecordComponentUpdateManyWithWhereWithoutPayrollRecordInput | Prisma.PayrollRecordComponentUpdateManyWithWhereWithoutPayrollRecordInput[]
  deleteMany?: Prisma.PayrollRecordComponentScalarWhereInput | Prisma.PayrollRecordComponentScalarWhereInput[]
}

export type PayrollRecordComponentCreateNestedManyWithoutPayrollComponentInput = {
  create?: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput> | Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput[] | Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput[]
  connectOrCreate?: Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollComponentInput | Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollComponentInput[]
  createMany?: Prisma.PayrollRecordComponentCreateManyPayrollComponentInputEnvelope
  connect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
}

export type PayrollRecordComponentUncheckedCreateNestedManyWithoutPayrollComponentInput = {
  create?: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput> | Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput[] | Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput[]
  connectOrCreate?: Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollComponentInput | Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollComponentInput[]
  createMany?: Prisma.PayrollRecordComponentCreateManyPayrollComponentInputEnvelope
  connect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
}

export type PayrollRecordComponentUpdateManyWithoutPayrollComponentNestedInput = {
  create?: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput> | Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput[] | Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput[]
  connectOrCreate?: Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollComponentInput | Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollComponentInput[]
  upsert?: Prisma.PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollComponentInput | Prisma.PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollComponentInput[]
  createMany?: Prisma.PayrollRecordComponentCreateManyPayrollComponentInputEnvelope
  set?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  disconnect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  delete?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  connect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  update?: Prisma.PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollComponentInput | Prisma.PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollComponentInput[]
  updateMany?: Prisma.PayrollRecordComponentUpdateManyWithWhereWithoutPayrollComponentInput | Prisma.PayrollRecordComponentUpdateManyWithWhereWithoutPayrollComponentInput[]
  deleteMany?: Prisma.PayrollRecordComponentScalarWhereInput | Prisma.PayrollRecordComponentScalarWhereInput[]
}

export type PayrollRecordComponentUncheckedUpdateManyWithoutPayrollComponentNestedInput = {
  create?: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput> | Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput[] | Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput[]
  connectOrCreate?: Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollComponentInput | Prisma.PayrollRecordComponentCreateOrConnectWithoutPayrollComponentInput[]
  upsert?: Prisma.PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollComponentInput | Prisma.PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollComponentInput[]
  createMany?: Prisma.PayrollRecordComponentCreateManyPayrollComponentInputEnvelope
  set?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  disconnect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  delete?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  connect?: Prisma.PayrollRecordComponentWhereUniqueInput | Prisma.PayrollRecordComponentWhereUniqueInput[]
  update?: Prisma.PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollComponentInput | Prisma.PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollComponentInput[]
  updateMany?: Prisma.PayrollRecordComponentUpdateManyWithWhereWithoutPayrollComponentInput | Prisma.PayrollRecordComponentUpdateManyWithWhereWithoutPayrollComponentInput[]
  deleteMany?: Prisma.PayrollRecordComponentScalarWhereInput | Prisma.PayrollRecordComponentScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type PayrollRecordComponentCreateWithoutPayrollRecordInput = {
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  PayrollComponent: Prisma.PayrollComponentCreateNestedOneWithoutPayrollRecordComponentInput
}

export type PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput = {
  id?: number
  componentId: number
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type PayrollRecordComponentCreateOrConnectWithoutPayrollRecordInput = {
  where: Prisma.PayrollRecordComponentWhereUniqueInput
  create: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput>
}

export type PayrollRecordComponentCreateManyPayrollRecordInputEnvelope = {
  data: Prisma.PayrollRecordComponentCreateManyPayrollRecordInput | Prisma.PayrollRecordComponentCreateManyPayrollRecordInput[]
  skipDuplicates?: boolean
}

export type PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollRecordInput = {
  where: Prisma.PayrollRecordComponentWhereUniqueInput
  update: Prisma.XOR<Prisma.PayrollRecordComponentUpdateWithoutPayrollRecordInput, Prisma.PayrollRecordComponentUncheckedUpdateWithoutPayrollRecordInput>
  create: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollRecordInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollRecordInput>
}

export type PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollRecordInput = {
  where: Prisma.PayrollRecordComponentWhereUniqueInput
  data: Prisma.XOR<Prisma.PayrollRecordComponentUpdateWithoutPayrollRecordInput, Prisma.PayrollRecordComponentUncheckedUpdateWithoutPayrollRecordInput>
}

export type PayrollRecordComponentUpdateManyWithWhereWithoutPayrollRecordInput = {
  where: Prisma.PayrollRecordComponentScalarWhereInput
  data: Prisma.XOR<Prisma.PayrollRecordComponentUpdateManyMutationInput, Prisma.PayrollRecordComponentUncheckedUpdateManyWithoutPayrollRecordInput>
}

export type PayrollRecordComponentScalarWhereInput = {
  AND?: Prisma.PayrollRecordComponentScalarWhereInput | Prisma.PayrollRecordComponentScalarWhereInput[]
  OR?: Prisma.PayrollRecordComponentScalarWhereInput[]
  NOT?: Prisma.PayrollRecordComponentScalarWhereInput | Prisma.PayrollRecordComponentScalarWhereInput[]
  id?: Prisma.IntFilter<"PayrollRecordComponent"> | number
  payrollRecordId?: Prisma.IntFilter<"PayrollRecordComponent"> | number
  componentId?: Prisma.IntFilter<"PayrollRecordComponent"> | number
  amount?: Prisma.DecimalFilter<"PayrollRecordComponent"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"PayrollRecordComponent"> | Date | string
}

export type PayrollRecordComponentCreateWithoutPayrollComponentInput = {
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  PayrollRecord: Prisma.PayrollRecordCreateNestedOneWithoutPayrollRecordComponentInput
}

export type PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput = {
  id?: number
  payrollRecordId: number
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type PayrollRecordComponentCreateOrConnectWithoutPayrollComponentInput = {
  where: Prisma.PayrollRecordComponentWhereUniqueInput
  create: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput>
}

export type PayrollRecordComponentCreateManyPayrollComponentInputEnvelope = {
  data: Prisma.PayrollRecordComponentCreateManyPayrollComponentInput | Prisma.PayrollRecordComponentCreateManyPayrollComponentInput[]
  skipDuplicates?: boolean
}

export type PayrollRecordComponentUpsertWithWhereUniqueWithoutPayrollComponentInput = {
  where: Prisma.PayrollRecordComponentWhereUniqueInput
  update: Prisma.XOR<Prisma.PayrollRecordComponentUpdateWithoutPayrollComponentInput, Prisma.PayrollRecordComponentUncheckedUpdateWithoutPayrollComponentInput>
  create: Prisma.XOR<Prisma.PayrollRecordComponentCreateWithoutPayrollComponentInput, Prisma.PayrollRecordComponentUncheckedCreateWithoutPayrollComponentInput>
}

export type PayrollRecordComponentUpdateWithWhereUniqueWithoutPayrollComponentInput = {
  where: Prisma.PayrollRecordComponentWhereUniqueInput
  data: Prisma.XOR<Prisma.PayrollRecordComponentUpdateWithoutPayrollComponentInput, Prisma.PayrollRecordComponentUncheckedUpdateWithoutPayrollComponentInput>
}

export type PayrollRecordComponentUpdateManyWithWhereWithoutPayrollComponentInput = {
  where: Prisma.PayrollRecordComponentScalarWhereInput
  data: Prisma.XOR<Prisma.PayrollRecordComponentUpdateManyMutationInput, Prisma.PayrollRecordComponentUncheckedUpdateManyWithoutPayrollComponentInput>
}

export type PayrollRecordComponentCreateManyPayrollRecordInput = {
  id?: number
  componentId: number
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type PayrollRecordComponentUpdateWithoutPayrollRecordInput = {
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  PayrollComponent?: Prisma.PayrollComponentUpdateOneRequiredWithoutPayrollRecordComponentNestedInput
}

export type PayrollRecordComponentUncheckedUpdateWithoutPayrollRecordInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  componentId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollRecordComponentUncheckedUpdateManyWithoutPayrollRecordInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  componentId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollRecordComponentCreateManyPayrollComponentInput = {
  id?: number
  payrollRecordId: number
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
}

export type PayrollRecordComponentUpdateWithoutPayrollComponentInput = {
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  PayrollRecord?: Prisma.PayrollRecordUpdateOneRequiredWithoutPayrollRecordComponentNestedInput
}

export type PayrollRecordComponentUncheckedUpdateWithoutPayrollComponentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  payrollRecordId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollRecordComponentUncheckedUpdateManyWithoutPayrollComponentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  payrollRecordId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PayrollRecordComponentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payrollRecordId?: boolean
  componentId?: boolean
  amount?: boolean
  createdAt?: boolean
  PayrollComponent?: boolean | Prisma.PayrollComponentDefaultArgs<ExtArgs>
  PayrollRecord?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payrollRecordComponent"]>

export type PayrollRecordComponentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payrollRecordId?: boolean
  componentId?: boolean
  amount?: boolean
  createdAt?: boolean
  PayrollComponent?: boolean | Prisma.PayrollComponentDefaultArgs<ExtArgs>
  PayrollRecord?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payrollRecordComponent"]>

export type PayrollRecordComponentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payrollRecordId?: boolean
  componentId?: boolean
  amount?: boolean
  createdAt?: boolean
  PayrollComponent?: boolean | Prisma.PayrollComponentDefaultArgs<ExtArgs>
  PayrollRecord?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payrollRecordComponent"]>

export type PayrollRecordComponentSelectScalar = {
  id?: boolean
  payrollRecordId?: boolean
  componentId?: boolean
  amount?: boolean
  createdAt?: boolean
}

export type PayrollRecordComponentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "payrollRecordId" | "componentId" | "amount" | "createdAt", ExtArgs["result"]["payrollRecordComponent"]>
export type PayrollRecordComponentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  PayrollComponent?: boolean | Prisma.PayrollComponentDefaultArgs<ExtArgs>
  PayrollRecord?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}
export type PayrollRecordComponentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  PayrollComponent?: boolean | Prisma.PayrollComponentDefaultArgs<ExtArgs>
  PayrollRecord?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}
export type PayrollRecordComponentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  PayrollComponent?: boolean | Prisma.PayrollComponentDefaultArgs<ExtArgs>
  PayrollRecord?: boolean | Prisma.PayrollRecordDefaultArgs<ExtArgs>
}

export type $PayrollRecordComponentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PayrollRecordComponent"
  objects: {
    PayrollComponent: Prisma.$PayrollComponentPayload<ExtArgs>
    PayrollRecord: Prisma.$PayrollRecordPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    payrollRecordId: number
    componentId: number
    amount: runtime.Decimal
    createdAt: Date
  }, ExtArgs["result"]["payrollRecordComponent"]>
  composites: {}
}

export type PayrollRecordComponentGetPayload<S extends boolean | null | undefined | PayrollRecordComponentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload, S>

export type PayrollRecordComponentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PayrollRecordComponentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PayrollRecordComponentCountAggregateInputType | true
  }

export interface PayrollRecordComponentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PayrollRecordComponent'], meta: { name: 'PayrollRecordComponent' } }
  /**
   * Find zero or one PayrollRecordComponent that matches the filter.
   * @param {PayrollRecordComponentFindUniqueArgs} args - Arguments to find a PayrollRecordComponent
   * @example
   * // Get one PayrollRecordComponent
   * const payrollRecordComponent = await prisma.payrollRecordComponent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PayrollRecordComponentFindUniqueArgs>(args: Prisma.SelectSubset<T, PayrollRecordComponentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PayrollRecordComponent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PayrollRecordComponentFindUniqueOrThrowArgs} args - Arguments to find a PayrollRecordComponent
   * @example
   * // Get one PayrollRecordComponent
   * const payrollRecordComponent = await prisma.payrollRecordComponent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PayrollRecordComponentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PayrollRecordComponentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PayrollRecordComponent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRecordComponentFindFirstArgs} args - Arguments to find a PayrollRecordComponent
   * @example
   * // Get one PayrollRecordComponent
   * const payrollRecordComponent = await prisma.payrollRecordComponent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PayrollRecordComponentFindFirstArgs>(args?: Prisma.SelectSubset<T, PayrollRecordComponentFindFirstArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PayrollRecordComponent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRecordComponentFindFirstOrThrowArgs} args - Arguments to find a PayrollRecordComponent
   * @example
   * // Get one PayrollRecordComponent
   * const payrollRecordComponent = await prisma.payrollRecordComponent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PayrollRecordComponentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PayrollRecordComponentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PayrollRecordComponents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRecordComponentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PayrollRecordComponents
   * const payrollRecordComponents = await prisma.payrollRecordComponent.findMany()
   * 
   * // Get first 10 PayrollRecordComponents
   * const payrollRecordComponents = await prisma.payrollRecordComponent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const payrollRecordComponentWithIdOnly = await prisma.payrollRecordComponent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PayrollRecordComponentFindManyArgs>(args?: Prisma.SelectSubset<T, PayrollRecordComponentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PayrollRecordComponent.
   * @param {PayrollRecordComponentCreateArgs} args - Arguments to create a PayrollRecordComponent.
   * @example
   * // Create one PayrollRecordComponent
   * const PayrollRecordComponent = await prisma.payrollRecordComponent.create({
   *   data: {
   *     // ... data to create a PayrollRecordComponent
   *   }
   * })
   * 
   */
  create<T extends PayrollRecordComponentCreateArgs>(args: Prisma.SelectSubset<T, PayrollRecordComponentCreateArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PayrollRecordComponents.
   * @param {PayrollRecordComponentCreateManyArgs} args - Arguments to create many PayrollRecordComponents.
   * @example
   * // Create many PayrollRecordComponents
   * const payrollRecordComponent = await prisma.payrollRecordComponent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PayrollRecordComponentCreateManyArgs>(args?: Prisma.SelectSubset<T, PayrollRecordComponentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PayrollRecordComponents and returns the data saved in the database.
   * @param {PayrollRecordComponentCreateManyAndReturnArgs} args - Arguments to create many PayrollRecordComponents.
   * @example
   * // Create many PayrollRecordComponents
   * const payrollRecordComponent = await prisma.payrollRecordComponent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PayrollRecordComponents and only return the `id`
   * const payrollRecordComponentWithIdOnly = await prisma.payrollRecordComponent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PayrollRecordComponentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PayrollRecordComponentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PayrollRecordComponent.
   * @param {PayrollRecordComponentDeleteArgs} args - Arguments to delete one PayrollRecordComponent.
   * @example
   * // Delete one PayrollRecordComponent
   * const PayrollRecordComponent = await prisma.payrollRecordComponent.delete({
   *   where: {
   *     // ... filter to delete one PayrollRecordComponent
   *   }
   * })
   * 
   */
  delete<T extends PayrollRecordComponentDeleteArgs>(args: Prisma.SelectSubset<T, PayrollRecordComponentDeleteArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PayrollRecordComponent.
   * @param {PayrollRecordComponentUpdateArgs} args - Arguments to update one PayrollRecordComponent.
   * @example
   * // Update one PayrollRecordComponent
   * const payrollRecordComponent = await prisma.payrollRecordComponent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PayrollRecordComponentUpdateArgs>(args: Prisma.SelectSubset<T, PayrollRecordComponentUpdateArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PayrollRecordComponents.
   * @param {PayrollRecordComponentDeleteManyArgs} args - Arguments to filter PayrollRecordComponents to delete.
   * @example
   * // Delete a few PayrollRecordComponents
   * const { count } = await prisma.payrollRecordComponent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PayrollRecordComponentDeleteManyArgs>(args?: Prisma.SelectSubset<T, PayrollRecordComponentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PayrollRecordComponents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRecordComponentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PayrollRecordComponents
   * const payrollRecordComponent = await prisma.payrollRecordComponent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PayrollRecordComponentUpdateManyArgs>(args: Prisma.SelectSubset<T, PayrollRecordComponentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PayrollRecordComponents and returns the data updated in the database.
   * @param {PayrollRecordComponentUpdateManyAndReturnArgs} args - Arguments to update many PayrollRecordComponents.
   * @example
   * // Update many PayrollRecordComponents
   * const payrollRecordComponent = await prisma.payrollRecordComponent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PayrollRecordComponents and only return the `id`
   * const payrollRecordComponentWithIdOnly = await prisma.payrollRecordComponent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PayrollRecordComponentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PayrollRecordComponentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PayrollRecordComponent.
   * @param {PayrollRecordComponentUpsertArgs} args - Arguments to update or create a PayrollRecordComponent.
   * @example
   * // Update or create a PayrollRecordComponent
   * const payrollRecordComponent = await prisma.payrollRecordComponent.upsert({
   *   create: {
   *     // ... data to create a PayrollRecordComponent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PayrollRecordComponent we want to update
   *   }
   * })
   */
  upsert<T extends PayrollRecordComponentUpsertArgs>(args: Prisma.SelectSubset<T, PayrollRecordComponentUpsertArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordComponentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PayrollRecordComponents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRecordComponentCountArgs} args - Arguments to filter PayrollRecordComponents to count.
   * @example
   * // Count the number of PayrollRecordComponents
   * const count = await prisma.payrollRecordComponent.count({
   *   where: {
   *     // ... the filter for the PayrollRecordComponents we want to count
   *   }
   * })
  **/
  count<T extends PayrollRecordComponentCountArgs>(
    args?: Prisma.Subset<T, PayrollRecordComponentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PayrollRecordComponentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PayrollRecordComponent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRecordComponentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PayrollRecordComponentAggregateArgs>(args: Prisma.Subset<T, PayrollRecordComponentAggregateArgs>): Prisma.PrismaPromise<GetPayrollRecordComponentAggregateType<T>>

  /**
   * Group by PayrollRecordComponent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRecordComponentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PayrollRecordComponentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PayrollRecordComponentGroupByArgs['orderBy'] }
      : { orderBy?: PayrollRecordComponentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PayrollRecordComponentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPayrollRecordComponentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PayrollRecordComponent model
 */
readonly fields: PayrollRecordComponentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PayrollRecordComponent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PayrollRecordComponentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  PayrollComponent<T extends Prisma.PayrollComponentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PayrollComponentDefaultArgs<ExtArgs>>): Prisma.Prisma__PayrollComponentClient<runtime.Types.Result.GetResult<Prisma.$PayrollComponentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  PayrollRecord<T extends Prisma.PayrollRecordDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PayrollRecordDefaultArgs<ExtArgs>>): Prisma.Prisma__PayrollRecordClient<runtime.Types.Result.GetResult<Prisma.$PayrollRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PayrollRecordComponent model
 */
export interface PayrollRecordComponentFieldRefs {
  readonly id: Prisma.FieldRef<"PayrollRecordComponent", 'Int'>
  readonly payrollRecordId: Prisma.FieldRef<"PayrollRecordComponent", 'Int'>
  readonly componentId: Prisma.FieldRef<"PayrollRecordComponent", 'Int'>
  readonly amount: Prisma.FieldRef<"PayrollRecordComponent", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"PayrollRecordComponent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PayrollRecordComponent findUnique
 */
export type PayrollRecordComponentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRecordComponent to fetch.
   */
  where: Prisma.PayrollRecordComponentWhereUniqueInput
}

/**
 * PayrollRecordComponent findUniqueOrThrow
 */
export type PayrollRecordComponentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRecordComponent to fetch.
   */
  where: Prisma.PayrollRecordComponentWhereUniqueInput
}

/**
 * PayrollRecordComponent findFirst
 */
export type PayrollRecordComponentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRecordComponent to fetch.
   */
  where?: Prisma.PayrollRecordComponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollRecordComponents to fetch.
   */
  orderBy?: Prisma.PayrollRecordComponentOrderByWithRelationInput | Prisma.PayrollRecordComponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PayrollRecordComponents.
   */
  cursor?: Prisma.PayrollRecordComponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollRecordComponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollRecordComponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayrollRecordComponents.
   */
  distinct?: Prisma.PayrollRecordComponentScalarFieldEnum | Prisma.PayrollRecordComponentScalarFieldEnum[]
}

/**
 * PayrollRecordComponent findFirstOrThrow
 */
export type PayrollRecordComponentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRecordComponent to fetch.
   */
  where?: Prisma.PayrollRecordComponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollRecordComponents to fetch.
   */
  orderBy?: Prisma.PayrollRecordComponentOrderByWithRelationInput | Prisma.PayrollRecordComponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PayrollRecordComponents.
   */
  cursor?: Prisma.PayrollRecordComponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollRecordComponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollRecordComponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayrollRecordComponents.
   */
  distinct?: Prisma.PayrollRecordComponentScalarFieldEnum | Prisma.PayrollRecordComponentScalarFieldEnum[]
}

/**
 * PayrollRecordComponent findMany
 */
export type PayrollRecordComponentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRecordComponents to fetch.
   */
  where?: Prisma.PayrollRecordComponentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollRecordComponents to fetch.
   */
  orderBy?: Prisma.PayrollRecordComponentOrderByWithRelationInput | Prisma.PayrollRecordComponentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PayrollRecordComponents.
   */
  cursor?: Prisma.PayrollRecordComponentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollRecordComponents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollRecordComponents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayrollRecordComponents.
   */
  distinct?: Prisma.PayrollRecordComponentScalarFieldEnum | Prisma.PayrollRecordComponentScalarFieldEnum[]
}

/**
 * PayrollRecordComponent create
 */
export type PayrollRecordComponentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
  /**
   * The data needed to create a PayrollRecordComponent.
   */
  data: Prisma.XOR<Prisma.PayrollRecordComponentCreateInput, Prisma.PayrollRecordComponentUncheckedCreateInput>
}

/**
 * PayrollRecordComponent createMany
 */
export type PayrollRecordComponentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PayrollRecordComponents.
   */
  data: Prisma.PayrollRecordComponentCreateManyInput | Prisma.PayrollRecordComponentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PayrollRecordComponent createManyAndReturn
 */
export type PayrollRecordComponentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * The data used to create many PayrollRecordComponents.
   */
  data: Prisma.PayrollRecordComponentCreateManyInput | Prisma.PayrollRecordComponentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PayrollRecordComponent update
 */
export type PayrollRecordComponentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
  /**
   * The data needed to update a PayrollRecordComponent.
   */
  data: Prisma.XOR<Prisma.PayrollRecordComponentUpdateInput, Prisma.PayrollRecordComponentUncheckedUpdateInput>
  /**
   * Choose, which PayrollRecordComponent to update.
   */
  where: Prisma.PayrollRecordComponentWhereUniqueInput
}

/**
 * PayrollRecordComponent updateMany
 */
export type PayrollRecordComponentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PayrollRecordComponents.
   */
  data: Prisma.XOR<Prisma.PayrollRecordComponentUpdateManyMutationInput, Prisma.PayrollRecordComponentUncheckedUpdateManyInput>
  /**
   * Filter which PayrollRecordComponents to update
   */
  where?: Prisma.PayrollRecordComponentWhereInput
  /**
   * Limit how many PayrollRecordComponents to update.
   */
  limit?: number
}

/**
 * PayrollRecordComponent updateManyAndReturn
 */
export type PayrollRecordComponentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * The data used to update PayrollRecordComponents.
   */
  data: Prisma.XOR<Prisma.PayrollRecordComponentUpdateManyMutationInput, Prisma.PayrollRecordComponentUncheckedUpdateManyInput>
  /**
   * Filter which PayrollRecordComponents to update
   */
  where?: Prisma.PayrollRecordComponentWhereInput
  /**
   * Limit how many PayrollRecordComponents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PayrollRecordComponent upsert
 */
export type PayrollRecordComponentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
  /**
   * The filter to search for the PayrollRecordComponent to update in case it exists.
   */
  where: Prisma.PayrollRecordComponentWhereUniqueInput
  /**
   * In case the PayrollRecordComponent found by the `where` argument doesn't exist, create a new PayrollRecordComponent with this data.
   */
  create: Prisma.XOR<Prisma.PayrollRecordComponentCreateInput, Prisma.PayrollRecordComponentUncheckedCreateInput>
  /**
   * In case the PayrollRecordComponent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PayrollRecordComponentUpdateInput, Prisma.PayrollRecordComponentUncheckedUpdateInput>
}

/**
 * PayrollRecordComponent delete
 */
export type PayrollRecordComponentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
  /**
   * Filter which PayrollRecordComponent to delete.
   */
  where: Prisma.PayrollRecordComponentWhereUniqueInput
}

/**
 * PayrollRecordComponent deleteMany
 */
export type PayrollRecordComponentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PayrollRecordComponents to delete
   */
  where?: Prisma.PayrollRecordComponentWhereInput
  /**
   * Limit how many PayrollRecordComponents to delete.
   */
  limit?: number
}

/**
 * PayrollRecordComponent without action
 */
export type PayrollRecordComponentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecordComponent
   */
  select?: Prisma.PayrollRecordComponentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecordComponent
   */
  omit?: Prisma.PayrollRecordComponentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordComponentInclude<ExtArgs> | null
}
