
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PayrollRun` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PayrollRun
 * 
 */
export type PayrollRunModel = runtime.Types.Result.DefaultSelection<Prisma.$PayrollRunPayload>

export type AggregatePayrollRun = {
  _count: PayrollRunCountAggregateOutputType | null
  _avg: PayrollRunAvgAggregateOutputType | null
  _sum: PayrollRunSumAggregateOutputType | null
  _min: PayrollRunMinAggregateOutputType | null
  _max: PayrollRunMaxAggregateOutputType | null
}

export type PayrollRunAvgAggregateOutputType = {
  id: number | null
  month: number | null
  year: number | null
  totalRecords: number | null
  processedRecords: number | null
  errorRecords: number | null
}

export type PayrollRunSumAggregateOutputType = {
  id: number | null
  month: number | null
  year: number | null
  totalRecords: number | null
  processedRecords: number | null
  errorRecords: number | null
}

export type PayrollRunMinAggregateOutputType = {
  id: number | null
  month: number | null
  year: number | null
  status: string | null
  totalRecords: number | null
  processedRecords: number | null
  errorRecords: number | null
  fileUrl: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PayrollRunMaxAggregateOutputType = {
  id: number | null
  month: number | null
  year: number | null
  status: string | null
  totalRecords: number | null
  processedRecords: number | null
  errorRecords: number | null
  fileUrl: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PayrollRunCountAggregateOutputType = {
  id: number
  month: number
  year: number
  status: number
  totalRecords: number
  processedRecords: number
  errorRecords: number
  fileUrl: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PayrollRunAvgAggregateInputType = {
  id?: true
  month?: true
  year?: true
  totalRecords?: true
  processedRecords?: true
  errorRecords?: true
}

export type PayrollRunSumAggregateInputType = {
  id?: true
  month?: true
  year?: true
  totalRecords?: true
  processedRecords?: true
  errorRecords?: true
}

export type PayrollRunMinAggregateInputType = {
  id?: true
  month?: true
  year?: true
  status?: true
  totalRecords?: true
  processedRecords?: true
  errorRecords?: true
  fileUrl?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type PayrollRunMaxAggregateInputType = {
  id?: true
  month?: true
  year?: true
  status?: true
  totalRecords?: true
  processedRecords?: true
  errorRecords?: true
  fileUrl?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type PayrollRunCountAggregateInputType = {
  id?: true
  month?: true
  year?: true
  status?: true
  totalRecords?: true
  processedRecords?: true
  errorRecords?: true
  fileUrl?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PayrollRunAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PayrollRun to aggregate.
   */
  where?: Prisma.PayrollRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollRuns to fetch.
   */
  orderBy?: Prisma.PayrollRunOrderByWithRelationInput | Prisma.PayrollRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PayrollRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PayrollRuns
  **/
  _count?: true | PayrollRunCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PayrollRunAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PayrollRunSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PayrollRunMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PayrollRunMaxAggregateInputType
}

export type GetPayrollRunAggregateType<T extends PayrollRunAggregateArgs> = {
      [P in keyof T & keyof AggregatePayrollRun]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePayrollRun[P]>
    : Prisma.GetScalarType<T[P], AggregatePayrollRun[P]>
}




export type PayrollRunGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PayrollRunWhereInput
  orderBy?: Prisma.PayrollRunOrderByWithAggregationInput | Prisma.PayrollRunOrderByWithAggregationInput[]
  by: Prisma.PayrollRunScalarFieldEnum[] | Prisma.PayrollRunScalarFieldEnum
  having?: Prisma.PayrollRunScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PayrollRunCountAggregateInputType | true
  _avg?: PayrollRunAvgAggregateInputType
  _sum?: PayrollRunSumAggregateInputType
  _min?: PayrollRunMinAggregateInputType
  _max?: PayrollRunMaxAggregateInputType
}

export type PayrollRunGroupByOutputType = {
  id: number
  month: number
  year: number
  status: string
  totalRecords: number | null
  processedRecords: number | null
  errorRecords: number | null
  fileUrl: string | null
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: PayrollRunCountAggregateOutputType | null
  _avg: PayrollRunAvgAggregateOutputType | null
  _sum: PayrollRunSumAggregateOutputType | null
  _min: PayrollRunMinAggregateOutputType | null
  _max: PayrollRunMaxAggregateOutputType | null
}

type GetPayrollRunGroupByPayload<T extends PayrollRunGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PayrollRunGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PayrollRunGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PayrollRunGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PayrollRunGroupByOutputType[P]>
      }
    >
  >



export type PayrollRunWhereInput = {
  AND?: Prisma.PayrollRunWhereInput | Prisma.PayrollRunWhereInput[]
  OR?: Prisma.PayrollRunWhereInput[]
  NOT?: Prisma.PayrollRunWhereInput | Prisma.PayrollRunWhereInput[]
  id?: Prisma.IntFilter<"PayrollRun"> | number
  month?: Prisma.IntFilter<"PayrollRun"> | number
  year?: Prisma.IntFilter<"PayrollRun"> | number
  status?: Prisma.StringFilter<"PayrollRun"> | string
  totalRecords?: Prisma.IntNullableFilter<"PayrollRun"> | number | null
  processedRecords?: Prisma.IntNullableFilter<"PayrollRun"> | number | null
  errorRecords?: Prisma.IntNullableFilter<"PayrollRun"> | number | null
  fileUrl?: Prisma.StringNullableFilter<"PayrollRun"> | string | null
  notes?: Prisma.StringNullableFilter<"PayrollRun"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PayrollRun"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PayrollRun"> | Date | string
  records?: Prisma.PayrollRecordListRelationFilter
  ValidationError?: Prisma.ValidationErrorListRelationFilter
}

export type PayrollRunOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalRecords?: Prisma.SortOrderInput | Prisma.SortOrder
  processedRecords?: Prisma.SortOrderInput | Prisma.SortOrder
  errorRecords?: Prisma.SortOrderInput | Prisma.SortOrder
  fileUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  records?: Prisma.PayrollRecordOrderByRelationAggregateInput
  ValidationError?: Prisma.ValidationErrorOrderByRelationAggregateInput
}

export type PayrollRunWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  month_year?: Prisma.PayrollRunMonthYearCompoundUniqueInput
  AND?: Prisma.PayrollRunWhereInput | Prisma.PayrollRunWhereInput[]
  OR?: Prisma.PayrollRunWhereInput[]
  NOT?: Prisma.PayrollRunWhereInput | Prisma.PayrollRunWhereInput[]
  month?: Prisma.IntFilter<"PayrollRun"> | number
  year?: Prisma.IntFilter<"PayrollRun"> | number
  status?: Prisma.StringFilter<"PayrollRun"> | string
  totalRecords?: Prisma.IntNullableFilter<"PayrollRun"> | number | null
  processedRecords?: Prisma.IntNullableFilter<"PayrollRun"> | number | null
  errorRecords?: Prisma.IntNullableFilter<"PayrollRun"> | number | null
  fileUrl?: Prisma.StringNullableFilter<"PayrollRun"> | string | null
  notes?: Prisma.StringNullableFilter<"PayrollRun"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PayrollRun"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PayrollRun"> | Date | string
  records?: Prisma.PayrollRecordListRelationFilter
  ValidationError?: Prisma.ValidationErrorListRelationFilter
}, "id" | "month_year">

export type PayrollRunOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalRecords?: Prisma.SortOrderInput | Prisma.SortOrder
  processedRecords?: Prisma.SortOrderInput | Prisma.SortOrder
  errorRecords?: Prisma.SortOrderInput | Prisma.SortOrder
  fileUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PayrollRunCountOrderByAggregateInput
  _avg?: Prisma.PayrollRunAvgOrderByAggregateInput
  _max?: Prisma.PayrollRunMaxOrderByAggregateInput
  _min?: Prisma.PayrollRunMinOrderByAggregateInput
  _sum?: Prisma.PayrollRunSumOrderByAggregateInput
}

export type PayrollRunScalarWhereWithAggregatesInput = {
  AND?: Prisma.PayrollRunScalarWhereWithAggregatesInput | Prisma.PayrollRunScalarWhereWithAggregatesInput[]
  OR?: Prisma.PayrollRunScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PayrollRunScalarWhereWithAggregatesInput | Prisma.PayrollRunScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PayrollRun"> | number
  month?: Prisma.IntWithAggregatesFilter<"PayrollRun"> | number
  year?: Prisma.IntWithAggregatesFilter<"PayrollRun"> | number
  status?: Prisma.StringWithAggregatesFilter<"PayrollRun"> | string
  totalRecords?: Prisma.IntNullableWithAggregatesFilter<"PayrollRun"> | number | null
  processedRecords?: Prisma.IntNullableWithAggregatesFilter<"PayrollRun"> | number | null
  errorRecords?: Prisma.IntNullableWithAggregatesFilter<"PayrollRun"> | number | null
  fileUrl?: Prisma.StringNullableWithAggregatesFilter<"PayrollRun"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"PayrollRun"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PayrollRun"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PayrollRun"> | Date | string
}

export type PayrollRunCreateInput = {
  month: number
  year: number
  status?: string
  totalRecords?: number | null
  processedRecords?: number | null
  errorRecords?: number | null
  fileUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  records?: Prisma.PayrollRecordCreateNestedManyWithoutPayrollRunInput
  ValidationError?: Prisma.ValidationErrorCreateNestedManyWithoutPayrollRunInput
}

export type PayrollRunUncheckedCreateInput = {
  id?: number
  month: number
  year: number
  status?: string
  totalRecords?: number | null
  processedRecords?: number | null
  errorRecords?: number | null
  fileUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  records?: Prisma.PayrollRecordUncheckedCreateNestedManyWithoutPayrollRunInput
  ValidationError?: Prisma.ValidationErrorUncheckedCreateNestedManyWithoutPayrollRunInput
}

export type PayrollRunUpdateInput = {
  month?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  processedRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  errorRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  records?: Prisma.PayrollRecordUpdateManyWithoutPayrollRunNestedInput
  ValidationError?: Prisma.ValidationErrorUpdateManyWithoutPayrollRunNestedInput
}

export type PayrollRunUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  month?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  processedRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  errorRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  records?: Prisma.PayrollRecordUncheckedUpdateManyWithoutPayrollRunNestedInput
  ValidationError?: Prisma.ValidationErrorUncheckedUpdateManyWithoutPayrollRunNestedInput
}

export type PayrollRunCreateManyInput = {
  id?: number
  month: number
  year: number
  status?: string
  totalRecords?: number | null
  processedRecords?: number | null
  errorRecords?: number | null
  fileUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PayrollRunUpdateManyMutationInput = {
  month?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  processedRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  errorRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollRunUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  month?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  processedRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  errorRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PayrollRunMonthYearCompoundUniqueInput = {
  month: number
  year: number
}

export type PayrollRunCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalRecords?: Prisma.SortOrder
  processedRecords?: Prisma.SortOrder
  errorRecords?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PayrollRunAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  totalRecords?: Prisma.SortOrder
  processedRecords?: Prisma.SortOrder
  errorRecords?: Prisma.SortOrder
}

export type PayrollRunMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalRecords?: Prisma.SortOrder
  processedRecords?: Prisma.SortOrder
  errorRecords?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PayrollRunMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalRecords?: Prisma.SortOrder
  processedRecords?: Prisma.SortOrder
  errorRecords?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PayrollRunSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  month?: Prisma.SortOrder
  year?: Prisma.SortOrder
  totalRecords?: Prisma.SortOrder
  processedRecords?: Prisma.SortOrder
  errorRecords?: Prisma.SortOrder
}

export type PayrollRunScalarRelationFilter = {
  is?: Prisma.PayrollRunWhereInput
  isNot?: Prisma.PayrollRunWhereInput
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PayrollRunCreateNestedOneWithoutRecordsInput = {
  create?: Prisma.XOR<Prisma.PayrollRunCreateWithoutRecordsInput, Prisma.PayrollRunUncheckedCreateWithoutRecordsInput>
  connectOrCreate?: Prisma.PayrollRunCreateOrConnectWithoutRecordsInput
  connect?: Prisma.PayrollRunWhereUniqueInput
}

export type PayrollRunUpdateOneRequiredWithoutRecordsNestedInput = {
  create?: Prisma.XOR<Prisma.PayrollRunCreateWithoutRecordsInput, Prisma.PayrollRunUncheckedCreateWithoutRecordsInput>
  connectOrCreate?: Prisma.PayrollRunCreateOrConnectWithoutRecordsInput
  upsert?: Prisma.PayrollRunUpsertWithoutRecordsInput
  connect?: Prisma.PayrollRunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PayrollRunUpdateToOneWithWhereWithoutRecordsInput, Prisma.PayrollRunUpdateWithoutRecordsInput>, Prisma.PayrollRunUncheckedUpdateWithoutRecordsInput>
}

export type PayrollRunCreateNestedOneWithoutValidationErrorInput = {
  create?: Prisma.XOR<Prisma.PayrollRunCreateWithoutValidationErrorInput, Prisma.PayrollRunUncheckedCreateWithoutValidationErrorInput>
  connectOrCreate?: Prisma.PayrollRunCreateOrConnectWithoutValidationErrorInput
  connect?: Prisma.PayrollRunWhereUniqueInput
}

export type PayrollRunUpdateOneRequiredWithoutValidationErrorNestedInput = {
  create?: Prisma.XOR<Prisma.PayrollRunCreateWithoutValidationErrorInput, Prisma.PayrollRunUncheckedCreateWithoutValidationErrorInput>
  connectOrCreate?: Prisma.PayrollRunCreateOrConnectWithoutValidationErrorInput
  upsert?: Prisma.PayrollRunUpsertWithoutValidationErrorInput
  connect?: Prisma.PayrollRunWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PayrollRunUpdateToOneWithWhereWithoutValidationErrorInput, Prisma.PayrollRunUpdateWithoutValidationErrorInput>, Prisma.PayrollRunUncheckedUpdateWithoutValidationErrorInput>
}

export type PayrollRunCreateWithoutRecordsInput = {
  month: number
  year: number
  status?: string
  totalRecords?: number | null
  processedRecords?: number | null
  errorRecords?: number | null
  fileUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  ValidationError?: Prisma.ValidationErrorCreateNestedManyWithoutPayrollRunInput
}

export type PayrollRunUncheckedCreateWithoutRecordsInput = {
  id?: number
  month: number
  year: number
  status?: string
  totalRecords?: number | null
  processedRecords?: number | null
  errorRecords?: number | null
  fileUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  ValidationError?: Prisma.ValidationErrorUncheckedCreateNestedManyWithoutPayrollRunInput
}

export type PayrollRunCreateOrConnectWithoutRecordsInput = {
  where: Prisma.PayrollRunWhereUniqueInput
  create: Prisma.XOR<Prisma.PayrollRunCreateWithoutRecordsInput, Prisma.PayrollRunUncheckedCreateWithoutRecordsInput>
}

export type PayrollRunUpsertWithoutRecordsInput = {
  update: Prisma.XOR<Prisma.PayrollRunUpdateWithoutRecordsInput, Prisma.PayrollRunUncheckedUpdateWithoutRecordsInput>
  create: Prisma.XOR<Prisma.PayrollRunCreateWithoutRecordsInput, Prisma.PayrollRunUncheckedCreateWithoutRecordsInput>
  where?: Prisma.PayrollRunWhereInput
}

export type PayrollRunUpdateToOneWithWhereWithoutRecordsInput = {
  where?: Prisma.PayrollRunWhereInput
  data: Prisma.XOR<Prisma.PayrollRunUpdateWithoutRecordsInput, Prisma.PayrollRunUncheckedUpdateWithoutRecordsInput>
}

export type PayrollRunUpdateWithoutRecordsInput = {
  month?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  processedRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  errorRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ValidationError?: Prisma.ValidationErrorUpdateManyWithoutPayrollRunNestedInput
}

export type PayrollRunUncheckedUpdateWithoutRecordsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  month?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  processedRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  errorRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ValidationError?: Prisma.ValidationErrorUncheckedUpdateManyWithoutPayrollRunNestedInput
}

export type PayrollRunCreateWithoutValidationErrorInput = {
  month: number
  year: number
  status?: string
  totalRecords?: number | null
  processedRecords?: number | null
  errorRecords?: number | null
  fileUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  records?: Prisma.PayrollRecordCreateNestedManyWithoutPayrollRunInput
}

export type PayrollRunUncheckedCreateWithoutValidationErrorInput = {
  id?: number
  month: number
  year: number
  status?: string
  totalRecords?: number | null
  processedRecords?: number | null
  errorRecords?: number | null
  fileUrl?: string | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  records?: Prisma.PayrollRecordUncheckedCreateNestedManyWithoutPayrollRunInput
}

export type PayrollRunCreateOrConnectWithoutValidationErrorInput = {
  where: Prisma.PayrollRunWhereUniqueInput
  create: Prisma.XOR<Prisma.PayrollRunCreateWithoutValidationErrorInput, Prisma.PayrollRunUncheckedCreateWithoutValidationErrorInput>
}

export type PayrollRunUpsertWithoutValidationErrorInput = {
  update: Prisma.XOR<Prisma.PayrollRunUpdateWithoutValidationErrorInput, Prisma.PayrollRunUncheckedUpdateWithoutValidationErrorInput>
  create: Prisma.XOR<Prisma.PayrollRunCreateWithoutValidationErrorInput, Prisma.PayrollRunUncheckedCreateWithoutValidationErrorInput>
  where?: Prisma.PayrollRunWhereInput
}

export type PayrollRunUpdateToOneWithWhereWithoutValidationErrorInput = {
  where?: Prisma.PayrollRunWhereInput
  data: Prisma.XOR<Prisma.PayrollRunUpdateWithoutValidationErrorInput, Prisma.PayrollRunUncheckedUpdateWithoutValidationErrorInput>
}

export type PayrollRunUpdateWithoutValidationErrorInput = {
  month?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  processedRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  errorRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  records?: Prisma.PayrollRecordUpdateManyWithoutPayrollRunNestedInput
}

export type PayrollRunUncheckedUpdateWithoutValidationErrorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  month?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  processedRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  errorRecords?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fileUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  records?: Prisma.PayrollRecordUncheckedUpdateManyWithoutPayrollRunNestedInput
}


/**
 * Count Type PayrollRunCountOutputType
 */

export type PayrollRunCountOutputType = {
  records: number
  ValidationError: number
}

export type PayrollRunCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  records?: boolean | PayrollRunCountOutputTypeCountRecordsArgs
  ValidationError?: boolean | PayrollRunCountOutputTypeCountValidationErrorArgs
}

/**
 * PayrollRunCountOutputType without action
 */
export type PayrollRunCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRunCountOutputType
   */
  select?: Prisma.PayrollRunCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PayrollRunCountOutputType without action
 */
export type PayrollRunCountOutputTypeCountRecordsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PayrollRecordWhereInput
}

/**
 * PayrollRunCountOutputType without action
 */
export type PayrollRunCountOutputTypeCountValidationErrorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ValidationErrorWhereInput
}


export type PayrollRunSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  month?: boolean
  year?: boolean
  status?: boolean
  totalRecords?: boolean
  processedRecords?: boolean
  errorRecords?: boolean
  fileUrl?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  records?: boolean | Prisma.PayrollRun$recordsArgs<ExtArgs>
  ValidationError?: boolean | Prisma.PayrollRun$ValidationErrorArgs<ExtArgs>
  _count?: boolean | Prisma.PayrollRunCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payrollRun"]>

export type PayrollRunSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  month?: boolean
  year?: boolean
  status?: boolean
  totalRecords?: boolean
  processedRecords?: boolean
  errorRecords?: boolean
  fileUrl?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["payrollRun"]>

export type PayrollRunSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  month?: boolean
  year?: boolean
  status?: boolean
  totalRecords?: boolean
  processedRecords?: boolean
  errorRecords?: boolean
  fileUrl?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["payrollRun"]>

export type PayrollRunSelectScalar = {
  id?: boolean
  month?: boolean
  year?: boolean
  status?: boolean
  totalRecords?: boolean
  processedRecords?: boolean
  errorRecords?: boolean
  fileUrl?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PayrollRunOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "month" | "year" | "status" | "totalRecords" | "processedRecords" | "errorRecords" | "fileUrl" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["payrollRun"]>
export type PayrollRunInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  records?: boolean | Prisma.PayrollRun$recordsArgs<ExtArgs>
  ValidationError?: boolean | Prisma.PayrollRun$ValidationErrorArgs<ExtArgs>
  _count?: boolean | Prisma.PayrollRunCountOutputTypeDefaultArgs<ExtArgs>
}
export type PayrollRunIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PayrollRunIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PayrollRunPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PayrollRun"
  objects: {
    records: Prisma.$PayrollRecordPayload<ExtArgs>[]
    ValidationError: Prisma.$ValidationErrorPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    month: number
    year: number
    status: string
    totalRecords: number | null
    processedRecords: number | null
    errorRecords: number | null
    fileUrl: string | null
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["payrollRun"]>
  composites: {}
}

export type PayrollRunGetPayload<S extends boolean | null | undefined | PayrollRunDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload, S>

export type PayrollRunCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PayrollRunFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PayrollRunCountAggregateInputType | true
  }

export interface PayrollRunDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PayrollRun'], meta: { name: 'PayrollRun' } }
  /**
   * Find zero or one PayrollRun that matches the filter.
   * @param {PayrollRunFindUniqueArgs} args - Arguments to find a PayrollRun
   * @example
   * // Get one PayrollRun
   * const payrollRun = await prisma.payrollRun.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PayrollRunFindUniqueArgs>(args: Prisma.SelectSubset<T, PayrollRunFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PayrollRunClient<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PayrollRun that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PayrollRunFindUniqueOrThrowArgs} args - Arguments to find a PayrollRun
   * @example
   * // Get one PayrollRun
   * const payrollRun = await prisma.payrollRun.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PayrollRunFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PayrollRunFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PayrollRunClient<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PayrollRun that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRunFindFirstArgs} args - Arguments to find a PayrollRun
   * @example
   * // Get one PayrollRun
   * const payrollRun = await prisma.payrollRun.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PayrollRunFindFirstArgs>(args?: Prisma.SelectSubset<T, PayrollRunFindFirstArgs<ExtArgs>>): Prisma.Prisma__PayrollRunClient<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PayrollRun that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRunFindFirstOrThrowArgs} args - Arguments to find a PayrollRun
   * @example
   * // Get one PayrollRun
   * const payrollRun = await prisma.payrollRun.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PayrollRunFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PayrollRunFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PayrollRunClient<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PayrollRuns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRunFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PayrollRuns
   * const payrollRuns = await prisma.payrollRun.findMany()
   * 
   * // Get first 10 PayrollRuns
   * const payrollRuns = await prisma.payrollRun.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const payrollRunWithIdOnly = await prisma.payrollRun.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PayrollRunFindManyArgs>(args?: Prisma.SelectSubset<T, PayrollRunFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PayrollRun.
   * @param {PayrollRunCreateArgs} args - Arguments to create a PayrollRun.
   * @example
   * // Create one PayrollRun
   * const PayrollRun = await prisma.payrollRun.create({
   *   data: {
   *     // ... data to create a PayrollRun
   *   }
   * })
   * 
   */
  create<T extends PayrollRunCreateArgs>(args: Prisma.SelectSubset<T, PayrollRunCreateArgs<ExtArgs>>): Prisma.Prisma__PayrollRunClient<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PayrollRuns.
   * @param {PayrollRunCreateManyArgs} args - Arguments to create many PayrollRuns.
   * @example
   * // Create many PayrollRuns
   * const payrollRun = await prisma.payrollRun.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PayrollRunCreateManyArgs>(args?: Prisma.SelectSubset<T, PayrollRunCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PayrollRuns and returns the data saved in the database.
   * @param {PayrollRunCreateManyAndReturnArgs} args - Arguments to create many PayrollRuns.
   * @example
   * // Create many PayrollRuns
   * const payrollRun = await prisma.payrollRun.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PayrollRuns and only return the `id`
   * const payrollRunWithIdOnly = await prisma.payrollRun.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PayrollRunCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PayrollRunCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PayrollRun.
   * @param {PayrollRunDeleteArgs} args - Arguments to delete one PayrollRun.
   * @example
   * // Delete one PayrollRun
   * const PayrollRun = await prisma.payrollRun.delete({
   *   where: {
   *     // ... filter to delete one PayrollRun
   *   }
   * })
   * 
   */
  delete<T extends PayrollRunDeleteArgs>(args: Prisma.SelectSubset<T, PayrollRunDeleteArgs<ExtArgs>>): Prisma.Prisma__PayrollRunClient<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PayrollRun.
   * @param {PayrollRunUpdateArgs} args - Arguments to update one PayrollRun.
   * @example
   * // Update one PayrollRun
   * const payrollRun = await prisma.payrollRun.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PayrollRunUpdateArgs>(args: Prisma.SelectSubset<T, PayrollRunUpdateArgs<ExtArgs>>): Prisma.Prisma__PayrollRunClient<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PayrollRuns.
   * @param {PayrollRunDeleteManyArgs} args - Arguments to filter PayrollRuns to delete.
   * @example
   * // Delete a few PayrollRuns
   * const { count } = await prisma.payrollRun.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PayrollRunDeleteManyArgs>(args?: Prisma.SelectSubset<T, PayrollRunDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PayrollRuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRunUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PayrollRuns
   * const payrollRun = await prisma.payrollRun.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PayrollRunUpdateManyArgs>(args: Prisma.SelectSubset<T, PayrollRunUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PayrollRuns and returns the data updated in the database.
   * @param {PayrollRunUpdateManyAndReturnArgs} args - Arguments to update many PayrollRuns.
   * @example
   * // Update many PayrollRuns
   * const payrollRun = await prisma.payrollRun.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PayrollRuns and only return the `id`
   * const payrollRunWithIdOnly = await prisma.payrollRun.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PayrollRunUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PayrollRunUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PayrollRun.
   * @param {PayrollRunUpsertArgs} args - Arguments to update or create a PayrollRun.
   * @example
   * // Update or create a PayrollRun
   * const payrollRun = await prisma.payrollRun.upsert({
   *   create: {
   *     // ... data to create a PayrollRun
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PayrollRun we want to update
   *   }
   * })
   */
  upsert<T extends PayrollRunUpsertArgs>(args: Prisma.SelectSubset<T, PayrollRunUpsertArgs<ExtArgs>>): Prisma.Prisma__PayrollRunClient<runtime.Types.Result.GetResult<Prisma.$PayrollRunPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PayrollRuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRunCountArgs} args - Arguments to filter PayrollRuns to count.
   * @example
   * // Count the number of PayrollRuns
   * const count = await prisma.payrollRun.count({
   *   where: {
   *     // ... the filter for the PayrollRuns we want to count
   *   }
   * })
  **/
  count<T extends PayrollRunCountArgs>(
    args?: Prisma.Subset<T, PayrollRunCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PayrollRunCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PayrollRun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRunAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PayrollRunAggregateArgs>(args: Prisma.Subset<T, PayrollRunAggregateArgs>): Prisma.PrismaPromise<GetPayrollRunAggregateType<T>>

  /**
   * Group by PayrollRun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayrollRunGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PayrollRunGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PayrollRunGroupByArgs['orderBy'] }
      : { orderBy?: PayrollRunGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PayrollRunGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPayrollRunGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PayrollRun model
 */
readonly fields: PayrollRunFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PayrollRun.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PayrollRunClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  records<T extends Prisma.PayrollRun$recordsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PayrollRun$recordsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayrollRecordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ValidationError<T extends Prisma.PayrollRun$ValidationErrorArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PayrollRun$ValidationErrorArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PayrollRun model
 */
export interface PayrollRunFieldRefs {
  readonly id: Prisma.FieldRef<"PayrollRun", 'Int'>
  readonly month: Prisma.FieldRef<"PayrollRun", 'Int'>
  readonly year: Prisma.FieldRef<"PayrollRun", 'Int'>
  readonly status: Prisma.FieldRef<"PayrollRun", 'String'>
  readonly totalRecords: Prisma.FieldRef<"PayrollRun", 'Int'>
  readonly processedRecords: Prisma.FieldRef<"PayrollRun", 'Int'>
  readonly errorRecords: Prisma.FieldRef<"PayrollRun", 'Int'>
  readonly fileUrl: Prisma.FieldRef<"PayrollRun", 'String'>
  readonly notes: Prisma.FieldRef<"PayrollRun", 'String'>
  readonly createdAt: Prisma.FieldRef<"PayrollRun", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PayrollRun", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PayrollRun findUnique
 */
export type PayrollRunFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRun to fetch.
   */
  where: Prisma.PayrollRunWhereUniqueInput
}

/**
 * PayrollRun findUniqueOrThrow
 */
export type PayrollRunFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRun to fetch.
   */
  where: Prisma.PayrollRunWhereUniqueInput
}

/**
 * PayrollRun findFirst
 */
export type PayrollRunFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRun to fetch.
   */
  where?: Prisma.PayrollRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollRuns to fetch.
   */
  orderBy?: Prisma.PayrollRunOrderByWithRelationInput | Prisma.PayrollRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PayrollRuns.
   */
  cursor?: Prisma.PayrollRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayrollRuns.
   */
  distinct?: Prisma.PayrollRunScalarFieldEnum | Prisma.PayrollRunScalarFieldEnum[]
}

/**
 * PayrollRun findFirstOrThrow
 */
export type PayrollRunFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRun to fetch.
   */
  where?: Prisma.PayrollRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollRuns to fetch.
   */
  orderBy?: Prisma.PayrollRunOrderByWithRelationInput | Prisma.PayrollRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PayrollRuns.
   */
  cursor?: Prisma.PayrollRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayrollRuns.
   */
  distinct?: Prisma.PayrollRunScalarFieldEnum | Prisma.PayrollRunScalarFieldEnum[]
}

/**
 * PayrollRun findMany
 */
export type PayrollRunFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
  /**
   * Filter, which PayrollRuns to fetch.
   */
  where?: Prisma.PayrollRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayrollRuns to fetch.
   */
  orderBy?: Prisma.PayrollRunOrderByWithRelationInput | Prisma.PayrollRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PayrollRuns.
   */
  cursor?: Prisma.PayrollRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayrollRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayrollRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayrollRuns.
   */
  distinct?: Prisma.PayrollRunScalarFieldEnum | Prisma.PayrollRunScalarFieldEnum[]
}

/**
 * PayrollRun create
 */
export type PayrollRunCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
  /**
   * The data needed to create a PayrollRun.
   */
  data: Prisma.XOR<Prisma.PayrollRunCreateInput, Prisma.PayrollRunUncheckedCreateInput>
}

/**
 * PayrollRun createMany
 */
export type PayrollRunCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PayrollRuns.
   */
  data: Prisma.PayrollRunCreateManyInput | Prisma.PayrollRunCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PayrollRun createManyAndReturn
 */
export type PayrollRunCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * The data used to create many PayrollRuns.
   */
  data: Prisma.PayrollRunCreateManyInput | Prisma.PayrollRunCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PayrollRun update
 */
export type PayrollRunUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
  /**
   * The data needed to update a PayrollRun.
   */
  data: Prisma.XOR<Prisma.PayrollRunUpdateInput, Prisma.PayrollRunUncheckedUpdateInput>
  /**
   * Choose, which PayrollRun to update.
   */
  where: Prisma.PayrollRunWhereUniqueInput
}

/**
 * PayrollRun updateMany
 */
export type PayrollRunUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PayrollRuns.
   */
  data: Prisma.XOR<Prisma.PayrollRunUpdateManyMutationInput, Prisma.PayrollRunUncheckedUpdateManyInput>
  /**
   * Filter which PayrollRuns to update
   */
  where?: Prisma.PayrollRunWhereInput
  /**
   * Limit how many PayrollRuns to update.
   */
  limit?: number
}

/**
 * PayrollRun updateManyAndReturn
 */
export type PayrollRunUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * The data used to update PayrollRuns.
   */
  data: Prisma.XOR<Prisma.PayrollRunUpdateManyMutationInput, Prisma.PayrollRunUncheckedUpdateManyInput>
  /**
   * Filter which PayrollRuns to update
   */
  where?: Prisma.PayrollRunWhereInput
  /**
   * Limit how many PayrollRuns to update.
   */
  limit?: number
}

/**
 * PayrollRun upsert
 */
export type PayrollRunUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
  /**
   * The filter to search for the PayrollRun to update in case it exists.
   */
  where: Prisma.PayrollRunWhereUniqueInput
  /**
   * In case the PayrollRun found by the `where` argument doesn't exist, create a new PayrollRun with this data.
   */
  create: Prisma.XOR<Prisma.PayrollRunCreateInput, Prisma.PayrollRunUncheckedCreateInput>
  /**
   * In case the PayrollRun was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PayrollRunUpdateInput, Prisma.PayrollRunUncheckedUpdateInput>
}

/**
 * PayrollRun delete
 */
export type PayrollRunDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
  /**
   * Filter which PayrollRun to delete.
   */
  where: Prisma.PayrollRunWhereUniqueInput
}

/**
 * PayrollRun deleteMany
 */
export type PayrollRunDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PayrollRuns to delete
   */
  where?: Prisma.PayrollRunWhereInput
  /**
   * Limit how many PayrollRuns to delete.
   */
  limit?: number
}

/**
 * PayrollRun.records
 */
export type PayrollRun$recordsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRecord
   */
  select?: Prisma.PayrollRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRecord
   */
  omit?: Prisma.PayrollRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRecordInclude<ExtArgs> | null
  where?: Prisma.PayrollRecordWhereInput
  orderBy?: Prisma.PayrollRecordOrderByWithRelationInput | Prisma.PayrollRecordOrderByWithRelationInput[]
  cursor?: Prisma.PayrollRecordWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PayrollRecordScalarFieldEnum | Prisma.PayrollRecordScalarFieldEnum[]
}

/**
 * PayrollRun.ValidationError
 */
export type PayrollRun$ValidationErrorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationErrorInclude<ExtArgs> | null
  where?: Prisma.ValidationErrorWhereInput
  orderBy?: Prisma.ValidationErrorOrderByWithRelationInput | Prisma.ValidationErrorOrderByWithRelationInput[]
  cursor?: Prisma.ValidationErrorWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ValidationErrorScalarFieldEnum | Prisma.ValidationErrorScalarFieldEnum[]
}

/**
 * PayrollRun without action
 */
export type PayrollRunDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayrollRun
   */
  select?: Prisma.PayrollRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayrollRun
   */
  omit?: Prisma.PayrollRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayrollRunInclude<ExtArgs> | null
}
