
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ValidationError` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ValidationError
 * 
 */
export type ValidationErrorModel = runtime.Types.Result.DefaultSelection<Prisma.$ValidationErrorPayload>

export type AggregateValidationError = {
  _count: ValidationErrorCountAggregateOutputType | null
  _min: ValidationErrorMinAggregateOutputType | null
  _max: ValidationErrorMaxAggregateOutputType | null
}

export type ValidationErrorMinAggregateOutputType = {
  id: string | null
  payrollRunId: string | null
  errorType: string | null
  staffNumber: string | null
  staffName: string | null
  message: string | null
  severity: string | null
  createdAt: Date | null
}

export type ValidationErrorMaxAggregateOutputType = {
  id: string | null
  payrollRunId: string | null
  errorType: string | null
  staffNumber: string | null
  staffName: string | null
  message: string | null
  severity: string | null
  createdAt: Date | null
}

export type ValidationErrorCountAggregateOutputType = {
  id: number
  payrollRunId: number
  errorType: number
  staffNumber: number
  staffName: number
  message: number
  severity: number
  createdAt: number
  _all: number
}


export type ValidationErrorMinAggregateInputType = {
  id?: true
  payrollRunId?: true
  errorType?: true
  staffNumber?: true
  staffName?: true
  message?: true
  severity?: true
  createdAt?: true
}

export type ValidationErrorMaxAggregateInputType = {
  id?: true
  payrollRunId?: true
  errorType?: true
  staffNumber?: true
  staffName?: true
  message?: true
  severity?: true
  createdAt?: true
}

export type ValidationErrorCountAggregateInputType = {
  id?: true
  payrollRunId?: true
  errorType?: true
  staffNumber?: true
  staffName?: true
  message?: true
  severity?: true
  createdAt?: true
  _all?: true
}

export type ValidationErrorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ValidationError to aggregate.
   */
  where?: Prisma.ValidationErrorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationErrors to fetch.
   */
  orderBy?: Prisma.ValidationErrorOrderByWithRelationInput | Prisma.ValidationErrorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ValidationErrorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationErrors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationErrors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ValidationErrors
  **/
  _count?: true | ValidationErrorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ValidationErrorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ValidationErrorMaxAggregateInputType
}

export type GetValidationErrorAggregateType<T extends ValidationErrorAggregateArgs> = {
      [P in keyof T & keyof AggregateValidationError]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateValidationError[P]>
    : Prisma.GetScalarType<T[P], AggregateValidationError[P]>
}




export type ValidationErrorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ValidationErrorWhereInput
  orderBy?: Prisma.ValidationErrorOrderByWithAggregationInput | Prisma.ValidationErrorOrderByWithAggregationInput[]
  by: Prisma.ValidationErrorScalarFieldEnum[] | Prisma.ValidationErrorScalarFieldEnum
  having?: Prisma.ValidationErrorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ValidationErrorCountAggregateInputType | true
  _min?: ValidationErrorMinAggregateInputType
  _max?: ValidationErrorMaxAggregateInputType
}

export type ValidationErrorGroupByOutputType = {
  id: string
  payrollRunId: string
  errorType: string
  staffNumber: string | null
  staffName: string | null
  message: string
  severity: string
  createdAt: Date
  _count: ValidationErrorCountAggregateOutputType | null
  _min: ValidationErrorMinAggregateOutputType | null
  _max: ValidationErrorMaxAggregateOutputType | null
}

type GetValidationErrorGroupByPayload<T extends ValidationErrorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ValidationErrorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ValidationErrorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ValidationErrorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ValidationErrorGroupByOutputType[P]>
      }
    >
  >



export type ValidationErrorWhereInput = {
  AND?: Prisma.ValidationErrorWhereInput | Prisma.ValidationErrorWhereInput[]
  OR?: Prisma.ValidationErrorWhereInput[]
  NOT?: Prisma.ValidationErrorWhereInput | Prisma.ValidationErrorWhereInput[]
  id?: Prisma.StringFilter<"ValidationError"> | string
  payrollRunId?: Prisma.StringFilter<"ValidationError"> | string
  errorType?: Prisma.StringFilter<"ValidationError"> | string
  staffNumber?: Prisma.StringNullableFilter<"ValidationError"> | string | null
  staffName?: Prisma.StringNullableFilter<"ValidationError"> | string | null
  message?: Prisma.StringFilter<"ValidationError"> | string
  severity?: Prisma.StringFilter<"ValidationError"> | string
  createdAt?: Prisma.DateTimeFilter<"ValidationError"> | Date | string
}

export type ValidationErrorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  payrollRunId?: Prisma.SortOrder
  errorType?: Prisma.SortOrder
  staffNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  staffName?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ValidationErrorWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ValidationErrorWhereInput | Prisma.ValidationErrorWhereInput[]
  OR?: Prisma.ValidationErrorWhereInput[]
  NOT?: Prisma.ValidationErrorWhereInput | Prisma.ValidationErrorWhereInput[]
  payrollRunId?: Prisma.StringFilter<"ValidationError"> | string
  errorType?: Prisma.StringFilter<"ValidationError"> | string
  staffNumber?: Prisma.StringNullableFilter<"ValidationError"> | string | null
  staffName?: Prisma.StringNullableFilter<"ValidationError"> | string | null
  message?: Prisma.StringFilter<"ValidationError"> | string
  severity?: Prisma.StringFilter<"ValidationError"> | string
  createdAt?: Prisma.DateTimeFilter<"ValidationError"> | Date | string
}, "id">

export type ValidationErrorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  payrollRunId?: Prisma.SortOrder
  errorType?: Prisma.SortOrder
  staffNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  staffName?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ValidationErrorCountOrderByAggregateInput
  _max?: Prisma.ValidationErrorMaxOrderByAggregateInput
  _min?: Prisma.ValidationErrorMinOrderByAggregateInput
}

export type ValidationErrorScalarWhereWithAggregatesInput = {
  AND?: Prisma.ValidationErrorScalarWhereWithAggregatesInput | Prisma.ValidationErrorScalarWhereWithAggregatesInput[]
  OR?: Prisma.ValidationErrorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ValidationErrorScalarWhereWithAggregatesInput | Prisma.ValidationErrorScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ValidationError"> | string
  payrollRunId?: Prisma.StringWithAggregatesFilter<"ValidationError"> | string
  errorType?: Prisma.StringWithAggregatesFilter<"ValidationError"> | string
  staffNumber?: Prisma.StringNullableWithAggregatesFilter<"ValidationError"> | string | null
  staffName?: Prisma.StringNullableWithAggregatesFilter<"ValidationError"> | string | null
  message?: Prisma.StringWithAggregatesFilter<"ValidationError"> | string
  severity?: Prisma.StringWithAggregatesFilter<"ValidationError"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ValidationError"> | Date | string
}

export type ValidationErrorCreateInput = {
  id?: string
  payrollRunId: string
  errorType: string
  staffNumber?: string | null
  staffName?: string | null
  message: string
  severity?: string
  createdAt?: Date | string
}

export type ValidationErrorUncheckedCreateInput = {
  id?: string
  payrollRunId: string
  errorType: string
  staffNumber?: string | null
  staffName?: string | null
  message: string
  severity?: string
  createdAt?: Date | string
}

export type ValidationErrorUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payrollRunId?: Prisma.StringFieldUpdateOperationsInput | string
  errorType?: Prisma.StringFieldUpdateOperationsInput | string
  staffNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  staffName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ValidationErrorUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payrollRunId?: Prisma.StringFieldUpdateOperationsInput | string
  errorType?: Prisma.StringFieldUpdateOperationsInput | string
  staffNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  staffName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ValidationErrorCreateManyInput = {
  id?: string
  payrollRunId: string
  errorType: string
  staffNumber?: string | null
  staffName?: string | null
  message: string
  severity?: string
  createdAt?: Date | string
}

export type ValidationErrorUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payrollRunId?: Prisma.StringFieldUpdateOperationsInput | string
  errorType?: Prisma.StringFieldUpdateOperationsInput | string
  staffNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  staffName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ValidationErrorUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payrollRunId?: Prisma.StringFieldUpdateOperationsInput | string
  errorType?: Prisma.StringFieldUpdateOperationsInput | string
  staffNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  staffName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ValidationErrorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payrollRunId?: Prisma.SortOrder
  errorType?: Prisma.SortOrder
  staffNumber?: Prisma.SortOrder
  staffName?: Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ValidationErrorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payrollRunId?: Prisma.SortOrder
  errorType?: Prisma.SortOrder
  staffNumber?: Prisma.SortOrder
  staffName?: Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ValidationErrorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payrollRunId?: Prisma.SortOrder
  errorType?: Prisma.SortOrder
  staffNumber?: Prisma.SortOrder
  staffName?: Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}



export type ValidationErrorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payrollRunId?: boolean
  errorType?: boolean
  staffNumber?: boolean
  staffName?: boolean
  message?: boolean
  severity?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["validationError"]>

export type ValidationErrorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payrollRunId?: boolean
  errorType?: boolean
  staffNumber?: boolean
  staffName?: boolean
  message?: boolean
  severity?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["validationError"]>

export type ValidationErrorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payrollRunId?: boolean
  errorType?: boolean
  staffNumber?: boolean
  staffName?: boolean
  message?: boolean
  severity?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["validationError"]>

export type ValidationErrorSelectScalar = {
  id?: boolean
  payrollRunId?: boolean
  errorType?: boolean
  staffNumber?: boolean
  staffName?: boolean
  message?: boolean
  severity?: boolean
  createdAt?: boolean
}

export type ValidationErrorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "payrollRunId" | "errorType" | "staffNumber" | "staffName" | "message" | "severity" | "createdAt", ExtArgs["result"]["validationError"]>

export type $ValidationErrorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ValidationError"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    payrollRunId: string
    errorType: string
    staffNumber: string | null
    staffName: string | null
    message: string
    severity: string
    createdAt: Date
  }, ExtArgs["result"]["validationError"]>
  composites: {}
}

export type ValidationErrorGetPayload<S extends boolean | null | undefined | ValidationErrorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload, S>

export type ValidationErrorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ValidationErrorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ValidationErrorCountAggregateInputType | true
  }

export interface ValidationErrorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ValidationError'], meta: { name: 'ValidationError' } }
  /**
   * Find zero or one ValidationError that matches the filter.
   * @param {ValidationErrorFindUniqueArgs} args - Arguments to find a ValidationError
   * @example
   * // Get one ValidationError
   * const validationError = await prisma.validationError.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ValidationErrorFindUniqueArgs>(args: Prisma.SelectSubset<T, ValidationErrorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ValidationErrorClient<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ValidationError that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ValidationErrorFindUniqueOrThrowArgs} args - Arguments to find a ValidationError
   * @example
   * // Get one ValidationError
   * const validationError = await prisma.validationError.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ValidationErrorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ValidationErrorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ValidationErrorClient<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ValidationError that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationErrorFindFirstArgs} args - Arguments to find a ValidationError
   * @example
   * // Get one ValidationError
   * const validationError = await prisma.validationError.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ValidationErrorFindFirstArgs>(args?: Prisma.SelectSubset<T, ValidationErrorFindFirstArgs<ExtArgs>>): Prisma.Prisma__ValidationErrorClient<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ValidationError that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationErrorFindFirstOrThrowArgs} args - Arguments to find a ValidationError
   * @example
   * // Get one ValidationError
   * const validationError = await prisma.validationError.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ValidationErrorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ValidationErrorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ValidationErrorClient<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ValidationErrors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationErrorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ValidationErrors
   * const validationErrors = await prisma.validationError.findMany()
   * 
   * // Get first 10 ValidationErrors
   * const validationErrors = await prisma.validationError.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const validationErrorWithIdOnly = await prisma.validationError.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ValidationErrorFindManyArgs>(args?: Prisma.SelectSubset<T, ValidationErrorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ValidationError.
   * @param {ValidationErrorCreateArgs} args - Arguments to create a ValidationError.
   * @example
   * // Create one ValidationError
   * const ValidationError = await prisma.validationError.create({
   *   data: {
   *     // ... data to create a ValidationError
   *   }
   * })
   * 
   */
  create<T extends ValidationErrorCreateArgs>(args: Prisma.SelectSubset<T, ValidationErrorCreateArgs<ExtArgs>>): Prisma.Prisma__ValidationErrorClient<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ValidationErrors.
   * @param {ValidationErrorCreateManyArgs} args - Arguments to create many ValidationErrors.
   * @example
   * // Create many ValidationErrors
   * const validationError = await prisma.validationError.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ValidationErrorCreateManyArgs>(args?: Prisma.SelectSubset<T, ValidationErrorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ValidationErrors and returns the data saved in the database.
   * @param {ValidationErrorCreateManyAndReturnArgs} args - Arguments to create many ValidationErrors.
   * @example
   * // Create many ValidationErrors
   * const validationError = await prisma.validationError.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ValidationErrors and only return the `id`
   * const validationErrorWithIdOnly = await prisma.validationError.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ValidationErrorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ValidationErrorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ValidationError.
   * @param {ValidationErrorDeleteArgs} args - Arguments to delete one ValidationError.
   * @example
   * // Delete one ValidationError
   * const ValidationError = await prisma.validationError.delete({
   *   where: {
   *     // ... filter to delete one ValidationError
   *   }
   * })
   * 
   */
  delete<T extends ValidationErrorDeleteArgs>(args: Prisma.SelectSubset<T, ValidationErrorDeleteArgs<ExtArgs>>): Prisma.Prisma__ValidationErrorClient<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ValidationError.
   * @param {ValidationErrorUpdateArgs} args - Arguments to update one ValidationError.
   * @example
   * // Update one ValidationError
   * const validationError = await prisma.validationError.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ValidationErrorUpdateArgs>(args: Prisma.SelectSubset<T, ValidationErrorUpdateArgs<ExtArgs>>): Prisma.Prisma__ValidationErrorClient<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ValidationErrors.
   * @param {ValidationErrorDeleteManyArgs} args - Arguments to filter ValidationErrors to delete.
   * @example
   * // Delete a few ValidationErrors
   * const { count } = await prisma.validationError.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ValidationErrorDeleteManyArgs>(args?: Prisma.SelectSubset<T, ValidationErrorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ValidationErrors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationErrorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ValidationErrors
   * const validationError = await prisma.validationError.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ValidationErrorUpdateManyArgs>(args: Prisma.SelectSubset<T, ValidationErrorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ValidationErrors and returns the data updated in the database.
   * @param {ValidationErrorUpdateManyAndReturnArgs} args - Arguments to update many ValidationErrors.
   * @example
   * // Update many ValidationErrors
   * const validationError = await prisma.validationError.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ValidationErrors and only return the `id`
   * const validationErrorWithIdOnly = await prisma.validationError.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ValidationErrorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ValidationErrorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ValidationError.
   * @param {ValidationErrorUpsertArgs} args - Arguments to update or create a ValidationError.
   * @example
   * // Update or create a ValidationError
   * const validationError = await prisma.validationError.upsert({
   *   create: {
   *     // ... data to create a ValidationError
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ValidationError we want to update
   *   }
   * })
   */
  upsert<T extends ValidationErrorUpsertArgs>(args: Prisma.SelectSubset<T, ValidationErrorUpsertArgs<ExtArgs>>): Prisma.Prisma__ValidationErrorClient<runtime.Types.Result.GetResult<Prisma.$ValidationErrorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ValidationErrors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationErrorCountArgs} args - Arguments to filter ValidationErrors to count.
   * @example
   * // Count the number of ValidationErrors
   * const count = await prisma.validationError.count({
   *   where: {
   *     // ... the filter for the ValidationErrors we want to count
   *   }
   * })
  **/
  count<T extends ValidationErrorCountArgs>(
    args?: Prisma.Subset<T, ValidationErrorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ValidationErrorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ValidationError.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationErrorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ValidationErrorAggregateArgs>(args: Prisma.Subset<T, ValidationErrorAggregateArgs>): Prisma.PrismaPromise<GetValidationErrorAggregateType<T>>

  /**
   * Group by ValidationError.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationErrorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ValidationErrorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ValidationErrorGroupByArgs['orderBy'] }
      : { orderBy?: ValidationErrorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ValidationErrorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetValidationErrorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ValidationError model
 */
readonly fields: ValidationErrorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ValidationError.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ValidationErrorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ValidationError model
 */
export interface ValidationErrorFieldRefs {
  readonly id: Prisma.FieldRef<"ValidationError", 'String'>
  readonly payrollRunId: Prisma.FieldRef<"ValidationError", 'String'>
  readonly errorType: Prisma.FieldRef<"ValidationError", 'String'>
  readonly staffNumber: Prisma.FieldRef<"ValidationError", 'String'>
  readonly staffName: Prisma.FieldRef<"ValidationError", 'String'>
  readonly message: Prisma.FieldRef<"ValidationError", 'String'>
  readonly severity: Prisma.FieldRef<"ValidationError", 'String'>
  readonly createdAt: Prisma.FieldRef<"ValidationError", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ValidationError findUnique
 */
export type ValidationErrorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * Filter, which ValidationError to fetch.
   */
  where: Prisma.ValidationErrorWhereUniqueInput
}

/**
 * ValidationError findUniqueOrThrow
 */
export type ValidationErrorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * Filter, which ValidationError to fetch.
   */
  where: Prisma.ValidationErrorWhereUniqueInput
}

/**
 * ValidationError findFirst
 */
export type ValidationErrorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * Filter, which ValidationError to fetch.
   */
  where?: Prisma.ValidationErrorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationErrors to fetch.
   */
  orderBy?: Prisma.ValidationErrorOrderByWithRelationInput | Prisma.ValidationErrorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ValidationErrors.
   */
  cursor?: Prisma.ValidationErrorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationErrors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationErrors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ValidationErrors.
   */
  distinct?: Prisma.ValidationErrorScalarFieldEnum | Prisma.ValidationErrorScalarFieldEnum[]
}

/**
 * ValidationError findFirstOrThrow
 */
export type ValidationErrorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * Filter, which ValidationError to fetch.
   */
  where?: Prisma.ValidationErrorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationErrors to fetch.
   */
  orderBy?: Prisma.ValidationErrorOrderByWithRelationInput | Prisma.ValidationErrorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ValidationErrors.
   */
  cursor?: Prisma.ValidationErrorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationErrors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationErrors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ValidationErrors.
   */
  distinct?: Prisma.ValidationErrorScalarFieldEnum | Prisma.ValidationErrorScalarFieldEnum[]
}

/**
 * ValidationError findMany
 */
export type ValidationErrorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * Filter, which ValidationErrors to fetch.
   */
  where?: Prisma.ValidationErrorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationErrors to fetch.
   */
  orderBy?: Prisma.ValidationErrorOrderByWithRelationInput | Prisma.ValidationErrorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ValidationErrors.
   */
  cursor?: Prisma.ValidationErrorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationErrors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationErrors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ValidationErrors.
   */
  distinct?: Prisma.ValidationErrorScalarFieldEnum | Prisma.ValidationErrorScalarFieldEnum[]
}

/**
 * ValidationError create
 */
export type ValidationErrorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * The data needed to create a ValidationError.
   */
  data: Prisma.XOR<Prisma.ValidationErrorCreateInput, Prisma.ValidationErrorUncheckedCreateInput>
}

/**
 * ValidationError createMany
 */
export type ValidationErrorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ValidationErrors.
   */
  data: Prisma.ValidationErrorCreateManyInput | Prisma.ValidationErrorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ValidationError createManyAndReturn
 */
export type ValidationErrorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * The data used to create many ValidationErrors.
   */
  data: Prisma.ValidationErrorCreateManyInput | Prisma.ValidationErrorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ValidationError update
 */
export type ValidationErrorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * The data needed to update a ValidationError.
   */
  data: Prisma.XOR<Prisma.ValidationErrorUpdateInput, Prisma.ValidationErrorUncheckedUpdateInput>
  /**
   * Choose, which ValidationError to update.
   */
  where: Prisma.ValidationErrorWhereUniqueInput
}

/**
 * ValidationError updateMany
 */
export type ValidationErrorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ValidationErrors.
   */
  data: Prisma.XOR<Prisma.ValidationErrorUpdateManyMutationInput, Prisma.ValidationErrorUncheckedUpdateManyInput>
  /**
   * Filter which ValidationErrors to update
   */
  where?: Prisma.ValidationErrorWhereInput
  /**
   * Limit how many ValidationErrors to update.
   */
  limit?: number
}

/**
 * ValidationError updateManyAndReturn
 */
export type ValidationErrorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * The data used to update ValidationErrors.
   */
  data: Prisma.XOR<Prisma.ValidationErrorUpdateManyMutationInput, Prisma.ValidationErrorUncheckedUpdateManyInput>
  /**
   * Filter which ValidationErrors to update
   */
  where?: Prisma.ValidationErrorWhereInput
  /**
   * Limit how many ValidationErrors to update.
   */
  limit?: number
}

/**
 * ValidationError upsert
 */
export type ValidationErrorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * The filter to search for the ValidationError to update in case it exists.
   */
  where: Prisma.ValidationErrorWhereUniqueInput
  /**
   * In case the ValidationError found by the `where` argument doesn't exist, create a new ValidationError with this data.
   */
  create: Prisma.XOR<Prisma.ValidationErrorCreateInput, Prisma.ValidationErrorUncheckedCreateInput>
  /**
   * In case the ValidationError was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ValidationErrorUpdateInput, Prisma.ValidationErrorUncheckedUpdateInput>
}

/**
 * ValidationError delete
 */
export type ValidationErrorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
  /**
   * Filter which ValidationError to delete.
   */
  where: Prisma.ValidationErrorWhereUniqueInput
}

/**
 * ValidationError deleteMany
 */
export type ValidationErrorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ValidationErrors to delete
   */
  where?: Prisma.ValidationErrorWhereInput
  /**
   * Limit how many ValidationErrors to delete.
   */
  limit?: number
}

/**
 * ValidationError without action
 */
export type ValidationErrorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationError
   */
  select?: Prisma.ValidationErrorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationError
   */
  omit?: Prisma.ValidationErrorOmit<ExtArgs> | null
}
